package main

import (
	"path/filepath"
	"strings"
	"testing"
)

// TestChangedRowCount pins the Go port of the frontend changedRows(blockRows(b))
// to the exact counts the real JS produces. The expected values were generated by
// running the verbatim Block.mjs functions (dedent4 → alignRows → changedRows) over
// the same fixtures; see the plan/commit notes. If the Go LCS ever drifts from the
// JS one, done/total in the UI would desync — this guards that.
func TestChangedRowCount(t *testing.T) {
	cases := []struct {
		name     string
		old, new string
		want     int
	}{
		{
			name: "modify_one",
			old:  "function f() {\n    return 1;\n}",
			new:  "function f() {\n    return 2;\n}",
			want: 1,
		},
		{
			// A removed line with no replacement is a filler row → counts as 1.
			name: "pure_delete",
			old:  "function f() {\n    $a = 1;\n    $b = 2;\n    return $a;\n}",
			new:  "function f() {\n    $a = 1;\n    return $a;\n}",
			want: 1,
		},
		{
			name: "pure_add",
			old:  "function f() {\n    return $a;\n}",
			new:  "function f() {\n    $log = true;\n    return $a;\n}",
			want: 1,
		},
		{
			// A whitespace-only re-indent must NOT count.
			name: "ws_only",
			old:  "function f() {\n    $a = array(1, 2);\n}",
			new:  "function f() {\n        $a = array(1, 2);\n}",
			want: 0,
		},
		{
			// One real change + one ws-only re-indent + one pure delete → 2.
			name: "mixed",
			old:  "function f() {\n    $a = 1;\n    $b = 2;\n    $c = 3;\n    return $a;\n}",
			new:  "function f() {\n    $a = 9;\n        $b = 2;\n    return $a;\n}",
			want: 2,
		},
		{
			name: "added_block",
			old:  "",
			new:  "function g() {\n    return 42;\n}",
			want: 3,
		},
		{
			// A blank line inside a wholly added function is diff noise (no
			// visible content to review) — it must NOT be counted as a 5th
			// changed row on top of the 4 real (non-blank) lines.
			name: "added_block_with_blank_line",
			old:  "",
			new:  "function g() {\n    $a = 1;\n\n    return $a;\n}",
			want: 4,
		},
		{
			// Same for a blank line inside a wholly removed function.
			name: "removed_block_with_blank_line",
			old:  "function g() {\n    $a = 1;\n\n    return $a;\n}",
			new:  "",
			want: 4,
		},
		{
			name: "removed_block",
			old:  "function g() {\n    return 42;\n}",
			new:  "",
			want: 3,
		},
		{
			// dedent4 strips a uniform 4-space indent before aligning.
			name: "dedented",
			old:  "    function h() {\n        return 1;\n    }",
			new:  "    function h() {\n        return 2;\n    }",
			want: 1,
		},
		{
			// Regression for a reported sidebar/header mismatch (PR 12896,
			// ProductFillRepository::update): a standalone blank-line insertion
			// (noise, must not count) elsewhere in the SAME block as a real
			// 1-old-line-replaced-by-several-new-lines edit (an unequal
			// del/ins pairing, all of which must count). Before the
			// rowHasContent fix (blank added/removed rows are noise), the
			// blank row inflated the total by one — this pins the combined
			// shape at the correct, lower count.
			name: "blank_line_plus_unequal_replace",
			old:  "function f() {\n    step1();\n    step2();\n    if (a()) {\n        b();\n    }\n}",
			new:  "function f() {\n    step1();\n\n    step2();\n    if (c()) {\n        d();\n        e();\n        f2();\n    } elseif (a()) {\n        b();\n    }\n}",
			want: 5,
		},
	}
	for _, c := range cases {
		t.Run(c.name, func(t *testing.T) {
			if got := changedRowCount(c.old, c.new); got != c.want {
				t.Fatalf("changedRowCount(%s) = %d, want %d", c.name, got, c.want)
			}
		})
	}
}

// TestBlockChangedRowCountReadsRenamedOldPath pins the /api/code+blockstats
// Go/JS-parity for a renamed block: the OLD side must be read from the block's
// pre-rename path (b.oldPath()), not its current File — otherwise the approve
// total would diff the new source against nothing (base worktree has no file
// at the new path yet) and count the whole method as added.
func TestBlockChangedRowCountReadsRenamedOldPath(t *testing.T) {
	baseDir, headDir := t.TempDir(), t.TempDir()
	oldPath := "app/Old/Foo.php"
	newPath := "app/New/Foo.php"
	oldSrc := "<?php\nclass Foo {\n    public function bar() {\n        return 1;\n    }\n}\n"
	newSrc := "<?php\nclass Foo {\n    public function bar() {\n        return 2;\n    }\n}\n"
	// The moved file lives at oldPath in base, newPath in head.
	writeFileT(t, filepath.Join(baseDir, oldPath), oldSrc)
	writeFileT(t, filepath.Join(headDir, newPath), newSrc)

	renamed := Block{File: newPath, OldFile: oldPath, Class: "Foo", Name: "bar"}
	if got := blockChangedRowCount(baseDir, headDir, renamed); got != 1 {
		t.Errorf("renamed block: changed rows = %d, want 1 (one edited line diffed against the old path)", got)
	}

	// Control: without OldFile the old side is read from the new path, absent in
	// base → the whole method reads as added (3 non-blank rows), proving the
	// oldPath redirection is what makes the count correct.
	control := Block{File: newPath, Class: "Foo", Name: "bar"}
	if got := blockChangedRowCount(baseDir, headDir, control); got == 1 {
		t.Errorf("control (no oldFile) unexpectedly matched the old path; want the added-method count, got %d", got)
	}
}

// TestRowForLineSharesRowSpaceWithApproveTotal pins the invariant every anchor
// consumer depends on: rowForLine (which turns a source line into a row index for
// an imported comment) and blockChangedRowCount (which sizes the approve total)
// must measure the SAME rows. Both now go through blockAlignedRows, so a block
// whose leading PHPDoc gets folded away for display shifts them together.
//
// Before that, rowForLine read the raw extractBlockSource while the approve total
// read the folded one, so on this block an imported comment landed 4 rows too high.
func TestRowForLineSharesRowSpaceWithApproveTotal(t *testing.T) {
	baseDir, headDir := t.TempDir(), t.TempDir()
	rel := "app/Foo.php"
	// A 4-line leading PHPDoc that enrichSignatureWithDocTypes folds into the
	// signature, so the displayed block starts at `public function bar(): int`.
	docSrc := func(ret string) string {
		return "<?php\nclass Foo {\n" +
			"    /**\n     * Does a thing.\n     * @return int\n     */\n" +
			"    public function bar() {\n        return " + ret + ";\n    }\n}\n"
	}
	writeFileT(t, filepath.Join(baseDir, rel), docSrc("1"))
	writeFileT(t, filepath.Join(headDir, rel), docSrc("2"))

	// Block.Line is the PHPDoc's own opening line (the scanner pulls it up, see
	// blocks-and-ingest.md), so the raw slice starts 4 lines above the signature.
	b := Block{File: rel, Class: "Foo", Name: "bar", Line: 3, EndLine: 9}

	rows, _, newSide := blockAlignedRows(baseDir, headDir, b)
	if want := b.Line + 4; newSide.Start != want {
		t.Fatalf("post-fold Start = %d, want %d (the 4 doc lines dropped)", newSide.Start, want)
	}
	// `return 2;` — the only changed line — is the one row the approve total counts.
	if got := blockChangedRowCount(baseDir, headDir, b); got != 1 {
		t.Fatalf("changed rows = %d, want 1", got)
	}

	// The same line, resolved by rowForLine, must land on that very row: a valid
	// index into the rows above, marked changed, and carrying the new text.
	row, ok := rowForLine(baseDir, headDir, b, 8, "RIGHT")
	if !ok {
		t.Fatal("rowForLine did not resolve line 8 (`return 2;`)")
	}
	if row < 0 || row >= len(rows) {
		t.Fatalf("row %d out of range for %d aligned rows", row, len(rows))
	}
	if got := strings.TrimSpace(rowDisplayText(rows[row])); got != "return 2;" {
		t.Errorf("row %d displays %q, want %q — the two row spaces disagree", row, got, "return 2;")
	}
	if !rowChanged(rows[row]) {
		t.Errorf("row %d is not marked changed, so it isn't the approvable row", row)
	}
}
