// chat_workflow.go — the claude_chat workflow: an embedded, multi-turn Claude
// conversation next to one existing review comment thread (see
// .claude/docs/tembed-workflows.md). One Execution per conversation; its
// Run ID is derived from the comment thread's own id, so starting it twice
// for the same comment is an idempotent no-op (StartWorkflowID) and the
// frontend never has to remember a separate chat Run ID of its own.
package main

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"path/filepath"
	"strings"
	"time"

	"github.com/reindert-vetter/tembed"
	"slash/modules/chat"
	"slash/modules/claude"
	"slash/modules/langpref"
)

// ClaudeChatInput starts (or, idempotently, re-ensures) a claude_chat
// Workflow Execution. CommentID is the existing task_code_comment thread this
// conversation hangs on — per product decision, a chat is always attached to
// an EXISTING comment thread and is normally a child workflow of it (see
// StartClaudeChat). Nothing auto-creates a comment for it: no comment (and no
// earlier conversation) means no chat, so the reviewer never gets a placeholder
// comment they didn't ask for.
type ClaudeChatInput struct {
	// Repo is the canonical repo string this PR belongs to: "" (absent) for the
	// primary repo — which is what every Execution started before multi-repo
	// existed carries, so replay of a stored history is unaffected — and
	// "owner/name" for any other configured repo. See repos.go.
	Repo      string `json:"repo,omitempty"`
	PR        int    `json:"pr"`
	CommentID string `json:"commentId"`
}

// ChatMessageSignal is the payload of a "message" Signal — one reviewer turn.
// ID is generated by the HTTP handler (like ReactionSignal.ID for a UI
// reaction), not inside the workflow body, so it stays deterministic under
// replay.
//
// Action rides along as a variant of this one Signal (mirrors
// ReactionSignal.Action, which the task_code_comment workflow already uses
// for "delete") — tembed can only WaitSignal on one name at a time, so a
// second signal name isn't an option. "" is the ordinary turn: runOneClaudeTurn
// itself already tries to get Claude real shell/file access in the
// PR's own shared local checkout (chat_checkout.go/prepareChatShellWorkDir)
// for EVERY turn, degrading silently to a tool-less completion when git/gh is
// unreachable — see that function's doc comment. chatActionEdit is kept only
// as a backward-compatible no-op synonym of ""; chatActionCommit
// fast-forward-pushes the shadow's edits onto the PR's real head branch and
// needs no Body at all (still the one dedicated path for that, alongside
// Claude's own Bash access being able to do the same on request).
//
// Context is the reviewer's selection at the time they sent this turn — file,
// old/new line range, a code excerpt (built client-side by RelatedPanel.mjs,
// only for a conversation's very first turn — see claude-chat-panel.md) — and
// is deliberately NEVER saved as part of the visible chat.Message.Body: it
// only enriches the PROMPT sent to the claude CLI (see runOneClaudeTurn's
// buildChatPrompt). The reviewer's own bubble must show exactly what they
// typed, nothing more.
type ChatMessageSignal struct {
	ID      string `json:"id"`
	Author  string `json:"author"`
	Body    string `json:"body"`
	Action  string `json:"action,omitempty"`
	Context string `json:"context,omitempty"`
}

// The three non-default ChatMessageSignal.Action values. Validated by the HTTP
// handler (tasks_api.go) before the Signal is ever sent — an unrecognized
// value is rejected there, so the workflow body only ever sees one of these
// four, and the branch it takes is thus fully determined by the Signal's own
// input (workflow-determinism.md).
const (
	chatActionEdit   = "edit"   // no-op synonym of "" — every turn already gets shell/Edit access
	chatActionCommit = "commit" // commit + land the checkout's edits
	// chatActionClear is "wis gesprek" (the palette's confirm-gated command,
	// see rootCommandsFor('claude') in home.mjs): wipe the transcript + the
	// stored claude session. Deliberately does NOT touch the PR's shared local
	// checkout any more (chat_checkout.go): unlike the old per-conversation
	// disposable shadow worktree, that checkout is shared by every conversation
	// of this PR, so wiping ONE conversation's transcript must never remove or
	// discard anything a DIFFERENT conversation (or a landing still in
	// progress) may still be relying on. The reviewer still sees a warning
	// about any pending (uncommitted/unlanded) work in that shared checkout
	// before confirming — see the read-only GET /api/chat/shadow-status
	// endpoint (tasks_api.go) and chatShadowPendingWarning (RelatedPanel.mjs) —
	// it is purely informational now, not a "will this get deleted" warning.
	chatActionClear = "clear"
	// chatActionRetry re-runs the LAST turn that finally failed (the automatic
	// backoff ladder below gave up on it), reusing that turn's own input —
	// same TurnID, same Body, same Context — so the failed bubble is replaced
	// rather than joined by a second copy of the reviewer's message. Carries no
	// Body of its own, like "commit"/"clear". A no-op when nothing failed.
	chatActionRetry = "retry"
	// chatActionCleanup resolves a chat.KindCleanupChoice bubble (the "what do
	// you want to do with what a cancelled turn left in the checkout?"
	// follow-up, see offerCancelCleanupIfDirty) — Body carries the reviewer's
	// chosen option verbatim (optDiscard/optStashManual/optStashAuto/
	// optKeepSeparate/optKeepCombined, chat_checkout.go). Deliberately its own
	// action rather than an ordinary reply: unlike chat.KindDirectoryDecision,
	// resolving this must NEVER resume the original request with a new Claude
	// call (see applyCancelCleanup's own doc comment) — it only performs the
	// chosen git housekeeping and reports the outcome.
	chatActionCleanup = "cleanup"
	// chatActionSeen marks the conversation as read up to its current last
	// message — sent by the UI the moment the reviewer actually opens a
	// conversation that has an unseen answer (see chat.Module.MarkSeen and
	// the "Openstaande chats" blue-eye indicator in
	// .claude/docs/claude-chat-panel.md). No Claude call, no user/assistant
	// turn — purely a bookkeeping write via its own Activity, same shape as
	// chatActionClear/Commit/Cleanup above.
	chatActionSeen = "seen"
	// chatActionAutoCheck marks the automatic first turn autoStartKiloCheck
	// (workflows.go) sends right after importing a kilo-code review comment —
	// never sent by the UI/HTTP handler, only by that server-side trigger.
	// Runs through the SAME path as an ordinary "" turn (saved as a user
	// message, a real Claude call with shell access) — it exists purely so the
	// saved chat.Message can carry chat.KindAutoCheck, which the frontend
	// badges as "automatische controle" instead of an ordinary typed message
	// (see claudeBubble/chatKindBadge, ClaudeChat.mjs).
	chatActionAutoCheck = "auto_check"
)

// chatRetryDelays is the automatic backoff ladder for a failed Claude call:
// the wait AFTER attempt i, so len(chatRetryDelays)+1 attempts in total (~93s
// of waiting). A var, not a const slice, purely so a test can shrink it —
// nothing else ever writes it.
//
// The waiting itself happens through w.Sleep (a durable timer that survives a
// restart), never a wall-clock sleep inside the workflow body, and the index
// is the loop counter — so which delay is used follows from the recorded
// history alone (.claude/rules/workflow-determinism.md).
var chatRetryDelays = []time.Duration{
	3 * time.Second,
	6 * time.Second,
	12 * time.Second,
	24 * time.Second,
	48 * time.Second,
}

// chatModelForAttempt picks the model for one attempt of a chat turn: Opus
// first, Sonnet from the third attempt on.
//
// Why not switch on the FIRST retry: the common failure here is a short
// capacity blip (an overloaded/aborted stream), which is usually gone after
// three seconds — and the reviewer picked this panel for Opus-quality answers,
// so a one-off hiccup should not cost that. Why switch at all: if TWO Opus
// attempts three seconds apart both fail, it is not a moment but a sustained
// capacity/quota problem on that model, and another model is then a better bet
// than waiting even longer.
//
// Deliberately NOT sticky for the rest of the conversation: the next reviewer
// turn starts at attempt 0 again, hence at Opus. A temporary outage must not
// silently downgrade the whole conversation, and keeping the choice a pure
// function of the attempt counter is exactly what keeps it deterministic under
// replay — nothing about it is stored or read from outside the workflow. The
// CLI session is unaffected: the model is a per-invocation flag, --resume
// keeps the same transcript either way.
func chatModelForAttempt(attempt int) string {
	if attempt < 2 {
		return claude.ModelOpus
	}
	return claude.ModelSonnet
}

// chatModelLabel is the short, reviewer-facing name of a model id (mirrored by
// MODEL_LABEL in src/ClaudeChat.mjs). An unknown id is shown verbatim.
func chatModelLabel(model string) string {
	switch model {
	case claude.ModelOpus:
		return "Opus"
	case claude.ModelSonnet:
		return "Sonnet"
	case claude.ModelHaiku:
		return "Haiku"
	}
	return model
}

// chatConversationRunID derives the claude_chat Execution's Run ID from the
// comment thread it hangs on. The comment id is already a short, filename-safe
// random hex string (or "gh-<id>" for an imported thread — see ids.go/
// comment_import.go), so no hashing is needed here, unlike explainRunID/
// resolveCallRunID (whose keys embed file paths).
func chatConversationRunID(commentID string) string {
	return "chat-" + commentID
}

// StartClaudeChat ensures the claude_chat Execution for commentID exists and
// returns its Run ID — the sanctioned UI write path (starting/reusing an
// Execution). Idempotent either way, and the Run ID is the same
// chatConversationRunID(commentID) in both routes below, so callers (the UI's
// message Signal, chat_merge.go, cleanup.go) never see the difference.
//
// The conversation belongs to the comment thread, so it is started as a CHILD
// workflow of that thread's own task_code_comment Execution — via its existing
// "reply" Signal with Action "chat" (tembed can only WaitSignal on one name at
// a time, so this rides along like "avatar"/"reanchor"/"delete"). Signalling is
// synchronous (SignalWorkflow advances the run inline, which starts the child
// inline too), so by the time this returns the chat run exists and can be
// signalled itself.
//
// CARVE-OUT: taskCodeCommentWorkflow ENDS on a delete (and, before resolving
// became reversible, also on a resolve — threads resolved back then are still
// completed, see workflows-comments.md), and a completed
// Execution can no longer receive a Signal. A thread whose Execution is gone or
// unreachable must not lose its chat, so those cases fall back to the original
// top-level StartWorkflowID (the run then simply has no ParentRunID — exactly
// what every chat created before this change looks like). Same "check the
// status BEFORE signalling" shape as applyChatCommentAction below.
func (m *TaskManager) StartClaudeChat(in ClaudeChatInput) (string, error) {
	runID := chatConversationRunID(in.CommentID)
	parent, ok := m.commentThreadRunID(in)
	if ok {
		err := m.Signal(parent, ReactionSignal{Action: "chat"})
		if err == nil {
			return runID, nil
		}
		m.logf("claude_chat: chat signal to thread %s failed, starting top-level instead: %v", parent, err)
	}
	return m.engine.StartWorkflowID(runID, WorkflowClaudeChat, in)
}

// commentThreadRunID resolves the task_code_comment Run ID that can host
// in.CommentID's conversation as a child, reporting false when that thread is
// unknown or can no longer be signalled (see StartClaudeChat's carve-out).
func (m *TaskManager) commentThreadRunID(in ClaudeChatInput) (string, bool) {
	if m.comments == nil {
		return "", false
	}
	ctx := context.Background()
	c, found, err := m.comments.Get(ctx, in.CommentID)
	if err != nil || !found || c.RunID == "" {
		m.logf("claude_chat: comment %s has no signallable thread, starting chat top-level (found=%v, err=%v)", in.CommentID, found, err)
		return "", false
	}
	status, err := m.engine.Status(c.RunID)
	if err != nil || status == tembed.StatusCompleted || status == tembed.StatusFailed {
		m.logf("claude_chat: thread %s not signallable (status=%q, err=%v), starting chat top-level", c.RunID, status, err)
		return "", false
	}
	return c.RunID, true
}

// claudeChatWorkflow is the durable definition. Deterministic: the only side
// effects are ExecuteActivity calls, and the loop tracks "is the assistant
// waiting on an answer to a question turn" purely from the PREVIOUS Activity
// result (pendingQuestionID), never from wall-clock/random state — safe under
// replay. It never completes — a long-lived per-conversation tracker, mould
// of taskCodeCommentWorkflow's reactions loop.
func claudeChatWorkflow(w *tembed.Workflow, input []byte) ([]byte, error) {
	var in ClaudeChatInput
	if err := json.Unmarshal(input, &in); err != nil {
		return nil, err
	}
	if err := w.ExecuteActivity("ensureChatConversation", in, nil); err != nil {
		return nil, fmt.Errorf("ensure chat conversation: %w", err)
	}

	pendingQuestionID := ""
	// lastFailedTurn is the input of the turn whose automatic retry ladder ran
	// out, kept so a later chatActionRetry Signal can run exactly that turn
	// again. Reconstructed identically on every replay (it only ever holds
	// values that came from a recorded Signal), so it is as deterministic as
	// pendingQuestionID above.
	var lastFailedTurn *chatTurnInput
	for {
		var sig ChatMessageSignal
		w.WaitSignal(SignalMessage, &sig)

		// "wis gesprek": wipe the transcript + session (and best-effort the shadow
		// worktree) via one Activity, drop any pending question, and go straight
		// back to WaitSignal — no user/assistant text turn, no Claude call. Decided
		// purely by sig.Action, part of the Signal's own recorded input, so this is
		// deterministic under replay exactly like the chatActionCommit branch below.
		if sig.Action == chatActionClear {
			if err := w.ExecuteActivity("clearChatConversation", chatCommitInput{
				PR: in.PR, ConversationID: in.CommentID,
			}, nil); err != nil {
				return nil, fmt.Errorf("clear chat conversation: %w", err)
			}
			pendingQuestionID = ""
			lastFailedTurn = nil
			continue
		}

		// "commit deze wijziging": hand this PR's shared-checkout edits
		// to the PR's own chat_merge queue, which serializes every conversation's
		// commit request for this PR so two of them landing around the same time
		// are merged one after another instead of racing each other's
		// fast-forward-only push (see chat_merge.go). No Claude call and no
		// user/assistant text turn here — the eventual outcome message is
		// recorded by processChatMerge, on the queue's OWN Execution, once it
		// gets to this request. This branch is decided purely by sig.Action, part
		// of the Signal's own recorded input — deterministic under replay.
		if sig.Action == chatActionCommit {
			if err := w.ExecuteActivity("enqueueChatMerge", chatCommitInput{
				PR: in.PR, ConversationID: in.CommentID, TurnID: sig.ID,
			}, nil); err != nil {
				return nil, fmt.Errorf("enqueue chat merge: %w", err)
			}
			continue
		}

		// Resolve a chat.KindCleanupChoice bubble left by a cancelled shell
		// attempt (offerCancelCleanupIfDirty) — no Claude call, ever: this only
		// performs git housekeeping and reports the outcome, on purpose (see
		// chatActionCleanup's own doc comment for why NOT the ordinary
		// answer/resume path). Decided purely by sig.Action, part of the
		// Signal's own recorded input — deterministic under replay.
		if sig.Action == chatActionCleanup {
			if err := w.ExecuteActivity("applyCancelCleanup", chatCancelCleanupInput{
				Repo: in.Repo, PR: in.PR, ConversationID: in.CommentID, Choice: sig.Body,
			}, nil); err != nil {
				return nil, fmt.Errorf("apply cancel cleanup: %w", err)
			}
			continue
		}

		// "Openstaande chats" blue-eye indicator (see chat.Module.MarkSeen's
		// own doc comment): the reviewer opened this conversation, stamp it as
		// read up to now. No Claude call, no user/assistant turn. Decided
		// purely by sig.Action, part of the Signal's own recorded input —
		// deterministic under replay.
		if sig.Action == chatActionSeen {
			if err := w.ExecuteActivity("markChatSeen", chatCommitInput{
				PR: in.PR, ConversationID: in.CommentID,
			}, nil); err != nil {
				return nil, fmt.Errorf("mark chat seen: %w", err)
			}
			continue
		}

		// "Opnieuw proberen": re-run the turn whose automatic ladder ran out,
		// with its OWN recorded input — same TurnID, so its failed bubble is
		// replaced rather than joined by a second copy of the reviewer's
		// message — and no new user turn/answer bookkeeping. Nothing failed
		// (yet) means nothing to do. Decided purely by sig.Action plus
		// lastFailedTurn, which itself only ever holds recorded values.
		turn := chatTurnInput{
			PR: in.PR, ConversationID: in.CommentID, Body: sig.Body, Action: sig.Action, TurnID: sig.ID,
			Context: sig.Context,
		}
		if sig.Action == chatActionRetry {
			if lastFailedTurn == nil {
				continue
			}
			turn = *lastFailedTurn
		} else {
			// The reviewer's next message answers the assistant's last question turn,
			// if there was one still open.
			if pendingQuestionID != "" {
				if err := w.ExecuteActivity("saveChatAnswer", map[string]any{
					"id": pendingQuestionID, "answer": sig.Body,
				}, nil); err != nil {
					return nil, fmt.Errorf("save chat answer: %w", err)
				}
				pendingQuestionID = ""
			}

			userKind := ""
			if sig.Action == chatActionAutoCheck {
				userKind = chat.KindAutoCheck
			}
			if err := w.ExecuteActivity("saveChatMessage", chat.Message{
				ID: sig.ID, ConversationID: in.CommentID, PR: in.PR, Role: "user", Body: sig.Body, Kind: userKind,
			}, nil); err != nil {
				return nil, fmt.Errorf("save chat user message: %w", err)
			}
		}

		result, err := runChatTurnWithRetries(w, turn)
		if err != nil {
			return nil, err
		}
		// The ladder is exhausted (KindError), or the reviewer cancelled it
		// (KindCancelled, which deliberately SKIPS the ladder — see
		// chatCancelledMessage): either way the turn stands as "mislukt"/
		// "afgebroken" until the reviewer asks for it again (chatActionRetry
		// above). Its input is kept verbatim so that retry is the very same
		// turn.
		if result.Message.Kind == chat.KindError || result.Message.Kind == chat.KindCancelled {
			failed := turn
			lastFailedTurn = &failed
			continue
		}
		lastFailedTurn = nil
		// chat.KindDirectoryDecision is still accepted here for a turn stored
		// before the work-directory choice moved out of the chat entirely
		// (nothing creates one any more) — an old, still-unanswered bubble
		// keeps its reviewer-reply round trip rather than becoming inert.
		if result.Message.Kind == chat.KindQuestion || result.Message.Kind == chat.KindDirectoryDecision {
			pendingQuestionID = result.Message.ID
		}

		// Phase 4: only when the reviewer explicitly asked for it, the assistant's
		// turn may carry a comment_action directive (parsed by parseAssistantTurn,
		// returned instead of a saved message by runOneClaudeTurn — see
		// chatTurnResult). Whether this Activity runs at all is decided purely by
		// the STORED result of the Activity just above (result.Action != nil),
		// mirroring the pendingQuestionID branch: deterministic under replay, never
		// dependent on live state. applyChatCommentAction is the only thing that
		// signals the comment thread's own task_code_comment Execution — via its
		// existing "reply" Signal (Source "ai"), never a direct write — and it also
		// records the one visible outcome turn (success or KindError).
		if result.Action != nil {
			if err := w.ExecuteActivity("applyChatCommentAction", chatCommentActionInput{
				PR: in.PR, ConversationID: in.CommentID, Directive: *result.Action, TurnID: turn.TurnID,
			}, nil); err != nil {
				return nil, fmt.Errorf("apply chat comment action: %w", err)
			}
		}

		// Tasks 1+2+4 (see "Automatic landing after a shell turn" in
		// .claude/docs/workflows-comments.md): whenever this turn's own Activity
		// result says the PR's shared checkout has something pending — an uncommitted
		// edit Claude left behind, or a local commit that never made it onto the
		// PR's pending ref — hand it to the SAME per-PR chat_merge queue the
		// (now unused-by-the-UI) manual "commit" action already used: it lands
		// fast-forward-only on the PR's local pending ref, auto-merges/resolves a
		// real conflict, refreshes the review tree, and reclaims the shadow
		// worktree — never a push, which stays the reviewer-gated todo row. A
		// dedicated TurnID (never the bare turn.TurnID) keeps the resulting
		// outcome message under its own id, so it can never overwrite the
		// assistant's own reply to this same turn (see chatMessageID). Decided
		// purely by result.NeedsLand, part of this turn's own recorded Activity
		// result — deterministic under replay.
		if result.NeedsLand {
			if err := w.ExecuteActivity("enqueueChatMerge", chatCommitInput{
				PR: in.PR, ConversationID: in.CommentID, TurnID: turn.TurnID + chatAutoLandTurnSuffix,
			}, nil); err != nil {
				return nil, fmt.Errorf("enqueue chat merge (auto-land): %w", err)
			}
		}
	}
}

// chatAutoLandTurnSuffix separates an automatic post-turn landing's own
// outcome message from the assistant's ordinary reply to the same reviewer
// turn — both would otherwise derive the same chatMessageID and the second
// SaveMessage (INSERT OR REPLACE) would silently overwrite the first.
const chatAutoLandTurnSuffix = "-autoland"

// chatTurnInput is runClaudeTurn's own Activity input — deliberately not
// ClaudeChatInput + a DB read of the transcript: the CLI's own --resume
// session already carries prior turns, so only the new message body needs to
// travel along (it's already in the workflow's history via the Signal).
// Action mirrors ChatMessageSignal.Action — kept for chatActionCommit
// dispatch (handled by the workflow before runOneClaudeTurn is even called)
// and as a backward-compatible field; runOneClaudeTurn itself no longer
// branches on it (see that function's doc comment).
// TurnID is the reviewer Signal's own id (ChatMessageSignal.ID, generated by
// the HTTP handler and therefore part of the recorded history) — see
// chatMessageID for why every message this turn writes derives its id from it.
// Context mirrors ChatMessageSignal.Context — folded into the CLI prompt by
// buildChatPrompt, never into the saved chat.Message.Body.
// Attempt/MaxAttempts are the position in runChatTurnWithRetries' backoff
// ladder (0-based / total). They decide the model (chatModelForAttempt) and
// the wording of a failed attempt's bubble, and they come from the workflow's
// own loop counter, so both stay deterministic under replay.
type chatTurnInput struct {
	// Repo is the canonical repo string this PR belongs to: "" (absent) for the
	// primary repo — which is what every Execution started before multi-repo
	// existed carries, so replay of a stored history is unaffected — and
	// "owner/name" for any other configured repo. See repos.go.
	Repo           string `json:"repo,omitempty"`
	PR             int    `json:"pr"`
	ConversationID string `json:"conversationId"`
	Body           string `json:"body"`
	Action         string `json:"action,omitempty"`
	TurnID         string `json:"turnId,omitempty"`
	Context        string `json:"context,omitempty"`
	Attempt        int    `json:"attempt,omitempty"`
	MaxAttempts    int    `json:"maxAttempts,omitempty"`
}

// runChatTurnWithRetries drives one reviewer turn through the automatic
// backoff ladder: run it, and while the Activity reports a still-retryable
// failure (chat.KindRetrying), wait chatRetryDelays[attempt] on a DURABLE
// timer and run it again. It returns the final result — a normal/question
// turn, a comment_action directive, or a chat.KindError message meaning the
// ladder is exhausted.
//
// Deterministic: the number of iterations and the delay index follow only from
// the recorded Activity results and the loop counter, the wait is w.Sleep (a
// timer event in the history, rescheduled after a restart), and nothing reads
// a live clock. Every attempt reuses the same TurnID, so each one REPLACES the
// previous attempt's row instead of adding a bubble (see chatMessageID).
func runChatTurnWithRetries(w *tembed.Workflow, turn chatTurnInput) (chatTurnResult, error) {
	for attempt := 0; ; attempt++ {
		// A FRESH zero value every iteration — load-bearing, not cosmetic.
		// chat.Message.Kind is `json:"kind,omitempty"`, so a successful attempt's
		// encoded result OMITS "kind" entirely; ExecuteActivity's decode (a plain
		// json.Unmarshal into this same pointer, see tembed's Workflow.ExecuteActivity)
		// only overwrites fields that ARE present, so reusing one `result`
		// variable across iterations would leave a PRIOR failed attempt's
		// chat.KindRetrying sitting in Message.Kind even once the retry
		// genuinely succeeded — which reads as "still retrying" below and drives
		// the ladder through every remaining rung for real, well past the
		// attempt that actually answered. Regression test:
		// TestRunChatTurnWithRetriesResetsResultPerAttempt.
		var result chatTurnResult
		arg := turn
		arg.Attempt = attempt
		arg.MaxAttempts = len(chatRetryDelays) + 1
		if err := w.ExecuteActivity("runClaudeTurn", arg, &result); err != nil {
			return result, fmt.Errorf("run claude turn: %w", err)
		}
		if result.Message.Kind != chat.KindRetrying {
			return result, nil
		}
		w.Sleep(chatRetryDelays[attempt])
	}
}

// chatCommitInput is commitCheckoutEditsAt's own Activity input (chat_checkout.go).
type chatCommitInput struct {
	// Repo is the canonical repo string this PR belongs to: "" (absent) for the
	// primary repo — which is what every Execution started before multi-repo
	// existed carries, so replay of a stored history is unaffected — and
	// "owner/name" for any other configured repo. See repos.go.
	Repo           string `json:"repo,omitempty"`
	PR             int    `json:"pr"`
	ConversationID string `json:"conversationId"`
	TurnID         string `json:"turnId,omitempty"`
}

// chatMessageID derives the id of an assistant message from the reviewer turn
// that caused it, so writing it twice overwrites one row instead of adding a
// second (modules/chat.SaveMessage is an INSERT OR REPLACE on this id).
//
// LOAD-BEARING for replay, not cosmetic: an Activity's side effects happen
// BEFORE its result is appended to the history, so a process killed in that
// window re-executes the whole Activity on recovery — with a random id that
// meant the reviewer ended up with two copies of the same assistant turn, one
// of them orphaned. turnId comes from the Signal (recorded input), so it is
// identical on every replay. `suffix` separates the two messages one turn can
// legitimately produce (the assistant's own reply, and a comment_action
// outcome). An empty turnId — an input recorded before this field existed —
// falls back to the old random id, which is exactly the previous behaviour.
func chatMessageID(turnID, suffix string) string {
	if turnID == "" {
		return "asst-" + newUIReactionID()
	}
	if suffix != "" {
		return "asst-" + turnID + "-" + suffix
	}
	return "asst-" + turnID
}

// chatActionReactionID is chatMessageID's counterpart for the ONE reaction a
// comment_action turn may post into the comment thread — same replay reasoning
// (comments.AddReaction is an INSERT OR IGNORE on this id, so a re-executed
// Activity re-posts nothing).
func chatActionReactionID(turnID string) string {
	if turnID == "" {
		return "sys-" + newUIReactionID()
	}
	return "sys-" + turnID + "-action"
}

// chatTurnResult is runClaudeTurn's own Activity return shape: the saved
// chat.Message (or, for a comment_action turn, a zero Message — see below)
// plus, only when the assistant's reply was a validated comment_action
// directive, the parsed action for the workflow to apply next via
// applyChatCommentAction. Kept separate from chat.Message itself (whose
// chat_messages persistence writes an explicit column list, never full-struct
// reflection — see modules/chat.SaveMessage) so this workflow-only handoff
// never leaks into modules/chat, which knows nothing about
// task_code_comment/ReactionSignal addressing.
// NeedsLand (tasks 1+2+4) is computed by the runClaudeTurn Activity's own
// registration in workflows.go, right after runOneClaudeTurn returns, via
// turnChangedCheckout + chatCheckoutNeedsLanding — never inside
// runOneClaudeTurn itself, so that
// function's own (chat.Message, *commentActionDirective) signature and its
// existing direct-call tests stay unchanged. Kept on this result (not
// re-derived in the workflow body) for the same determinism reason
// Action/pendingQuestionID are: the workflow body must decide whether to run
// a further Activity purely from a STORED Activity result, never from a live
// git read of its own.
type chatTurnResult struct {
	Message   chat.Message            `json:"message"`
	Action    *commentActionDirective `json:"action,omitempty"`
	NeedsLand bool                    `json:"needsLand,omitempty"`
}

// commentActionDirective is the parsed, but NOT YET validated, shape of a
// reviewer-requested {"type":"comment_action",...} assistant directive.
// CommentID is re-validated by applyChatCommentAction against the
// conversation's own thread before anything is signalled — see
// parseAssistantTurn and .claude/docs/workflows-comments.md ("claude_chat").
type commentActionDirective struct {
	CommentID string `json:"commentId"`
	Action    string `json:"action"` // "reply" | "resolve"
	Body      string `json:"body"`   // required for "reply", ignored for "resolve"
}

// chatCommentActionInput is applyChatCommentAction's own Activity input.
type chatCommentActionInput struct {
	// Repo is the canonical repo string this PR belongs to: "" (absent) for the
	// primary repo — which is what every Execution started before multi-repo
	// existed carries, so replay of a stored history is unaffected — and
	// "owner/name" for any other configured repo. See repos.go.
	Repo           string                 `json:"repo,omitempty"`
	PR             int                    `json:"pr"`
	ConversationID string                 `json:"conversationId"`
	Directive      commentActionDirective `json:"directive"`
	TurnID         string                 `json:"turnId,omitempty"`
}

// assistantDirective is the strict JSON shape claude.ChatSystemPrompt asks
// the model to use — a clarifying question with a few choices ("question"),
// or, only on the reviewer's explicit request, an action to apply to the left
// comment thread ("comment_action", Phase 4). Anything that doesn't parse as
// one of these two recognized shapes is treated as a plain text turn.
type assistantDirective struct {
	Type     string   `json:"type"` // "question" | "comment_action"
	Question string   `json:"question"`
	Options  []string `json:"options"`
	// The following three fields are comment_action-only.
	Action    string `json:"action"` // "reply" | "resolve"
	CommentID string `json:"commentId"`
	Body      string `json:"body"`
}

// maxChatQuestionOptions caps how many choices a question turn offers,
// per product decision ("max 3, met eigen input als vierde optie" — the
// reviewer can always type free text instead of picking one, so the UI never
// needs a real 4th option).
const maxChatQuestionOptions = 3

// buildChatPrompt folds the reviewer's selection context (if any — only sent
// for a conversation's first turn, see RelatedPanel.mjs's claudeContextBlock)
// in FRONT of the typed message for the CLI's own Prompt, so Claude sees what
// file/line/code the reviewer is asking about. Deliberately never used for
// what gets SAVED as chat.Message.Body (see saveChatMessage in
// claudeChatWorkflow above) — the reviewer's own bubble must show only what
// they typed. context == "" (every turn after the first, or no cursor info
// available) is a plain pass-through.
//
// arg.Action == chatActionEdit is kept only for backward compatibility with
// any already-recorded history/external caller — runOneClaudeTurn no longer
// branches on it at all (see that function's own doc comment for the current,
// two-step tool-access design, task 3).
func buildChatPrompt(selectionContext, body string) string {
	if selectionContext == "" {
		return body
	}
	return selectionContext + "\n\n" + body
}

// chatCommentIDNote is the dynamic, call-specific tail every chat system
// prompt gets appended (the static prompt files are call-independent text —
// see modules/claude/prompts.go): the conversation's own comment id, which
// the comment_action directive needs to echo back as "commentId". Harmless
// for a turn that never uses the directive. Shared by both attempts of a
// two-step turn (see runOneClaudeTurn) so neither has to repeat the wording.
func chatCommentIDNote(conversationID string) string {
	return "\n\nHet id van DEZE comment-thread (gebruik dit exact als \"commentId\" in het comment_action-format): " + conversationID
}

// chatNeedWriteContinuationPrompt is the synthetic user prompt sent on a
// turn's SECOND, shell-enabled call (see runOneClaudeTurn) — resuming the
// SAME session Claude used for its cheap read-only first attempt, so it
// keeps whatever it already learned there, plus the reviewer's own original
// message (already part of that session's history). Claude's own first-call
// reply was the bare {"type":"need_write"} directive and carries no content
// of its own, so this is what actually prompts the second call.
const chatNeedWriteContinuationPrompt = "Je hebt nu Edit en een echte shell (Bash) beschikbaar, in de lokale checkout van de reviewer. Ga verder met het oorspronkelijke verzoek."

// chatFailureMessage words + persists one failed claude CLI call as a visible
// turn (see chatFailureTurn) — shared by both attempts of runOneClaudeTurn's
// two-step call, so a CLI failure on either one degrades the same way.
// callErr is RunChat's own returned error, passed through so chatFailureTurn
// can surface the CLI's real explanation when there is one (see
// claude.ChatCallError) instead of only ever generic wording.
func chatFailureMessage(ctx context.Context, cm *chat.Module, arg chatTurnInput, model string, callErr error) chat.Message {
	kind, body := chatFailureTurn(arg.Attempt, model, callErr)
	msg := chat.Message{
		ID: chatMessageID(arg.TurnID, ""), ConversationID: arg.ConversationID, PR: arg.PR,
		Role: "assistant", Kind: kind, Body: body, Model: model,
	}
	_ = cm.SaveMessage(ctx, msg)
	return msg
}

// chatCancelledMessage words + persists the reviewer's own "Stop" as a
// terminal turn — the honest counterpart to chatFailureMessage: nothing
// actually went wrong, the reviewer chose to interrupt it, so both the Kind
// and the wording must say exactly that, never "foutmelding" (see
// chat.KindCancelled's own doc comment in modules/chat/chat.go). `ctx` here
// is always the Activity's ORIGINAL, uncancelled context (never the runCtx
// that just cancelled) — see runOneClaudeTurn's own doc comment — so the
// message can still actually be persisted.
func chatCancelledMessage(ctx context.Context, cm *chat.Module, arg chatTurnInput, model string) chat.Message {
	msg := chat.Message{
		ID: chatMessageID(arg.TurnID, ""), ConversationID: arg.ConversationID, PR: arg.PR,
		Role: "assistant", Kind: chat.KindCancelled, Model: model,
		Body: "Afgebroken op jouw verzoek.",
	}
	_ = cm.SaveMessage(ctx, msg)
	return msg
}

// offerCancelCleanupIfDirty saves a follow-up chat.KindCleanupChoice bubble
// offering to discard/stash whatever a just-cancelled SHELL attempt left
// behind in dir, ONLY when dir turns out to actually be dirty — "alleen
// aanbieden als er echt iets is aangepast" (reviewer decision): a cancel that
// landed before Claude's own Edit/Bash tool calls touched anything leaves
// nothing to clean up, and this is then a silent no-op.
//
// Deliberately its own small mechanism, NOT chat_checkout.go's
// chatCheckoutDecision/a.Pending machinery (see applyCancelCleanup's own doc
// comment for why): that one is a PR-wide setting answered in its own overlay,
// while this question is about THIS cancelled turn and belongs exactly where
// the reviewer cancelled it. Its visible badge says "opruimen na afbreken" —
// the word "checkout" appears nowhere in it, see the naming rule in
// .claude/docs/workflows-comments.md.
func offerCancelCleanupIfDirty(ctx context.Context, cm *chat.Module, arg chatTurnInput, dir string) {
	dirty, err := checkoutIsDirty(ctx, dir)
	if err != nil || !dirty {
		return
	}
	msg := chat.Message{
		ID: chatMessageID(arg.TurnID, "cleanup"), ConversationID: arg.ConversationID, PR: arg.PR,
		Role: "assistant", Kind: chat.KindCleanupChoice,
		Body:    fmt.Sprintf("De afgebroken beurt liet niet-gecommitte wijzigingen achter in `%s`. Wat wil je daarmee doen?", dir),
		Options: []string{optDiscard, optStashManual, optStashAuto, optKeepSeparate, optKeepCombined},
	}
	_ = cm.SaveMessage(ctx, msg)
}

// isNeedWriteDirective reports whether text is exactly the strict
// {"type":"need_write"} directive (task 3's escalation signal) — the cheap
// read-only first attempt's way of saying "I need Edit/Bash to do this".
// Anything else (plain text, a question/comment_action directive, malformed
// JSON) is not an escalation and is left for parseAssistantTurn to interpret
// as usual.
func isNeedWriteDirective(text string) bool {
	trimmed := strings.TrimSpace(text)
	if !strings.HasPrefix(trimmed, "{") {
		return false
	}
	var d struct {
		Type string `json:"type"`
	}
	if err := json.Unmarshal([]byte(trimmed), &d); err != nil {
		return false
	}
	return d.Type == "need_write"
}

// writeRefusalPhrases are the literal, lowercased fragments that mean "this
// reply is Claude saying it cannot write here" — the prose it falls back to
// instead of emitting {"type":"need_write"} (see looksLikeWriteRefusal). Kept
// as an explicit, deliberately SHORT list of wordings actually observed in
// reviewer-reported turns, never a general "does this sound negative" test:
// a missed escalation only costs the reviewer one more message, while a false
// positive costs the one code-turn slot (chat_write_gate.go) plus a real
// git/gh work-directory resolve for a turn that never needed either.
var writeRefusalPhrases = []string{
	"geen edit",           // "ik heb deze beurt alsnog geen Edit/Bash", "geen Edit-tool"
	"geen bash",           // "geen Bash", "geen Bash-tool"
	"geen shell",          // the read-only prompt's own wording, echoed back
	"geen schrijftoegang", //
	"geen schrijfrechten", //
	"kan niets aanpassen", // "ik kan niets aanpassen, committen of uitvoeren"
	"kan ik niets aanpassen",
}

// stripCodeFencesForScan removes every ```-fenced block from text so a phrase
// scan only ever reads Claude's own PROSE. A write-refusal reply typically
// carries the proposed replacement as a fence right below it, and that fence
// holds arbitrary source/comment text that must never be able to trigger (or
// suppress) an escalation.
func stripCodeFencesForScan(text string) string {
	parts := strings.Split(text, "```")
	var b strings.Builder
	for i, part := range parts {
		if i%2 == 0 { // even segments sit OUTSIDE a fence
			b.WriteString(part)
			b.WriteString("\n")
		}
	}
	return b.String()
}

// looksLikeWriteRefusal reports whether an otherwise ordinary prose reply is
// really Claude saying "I cannot edit/run anything this turn" — the failure
// mode the strict {"type":"need_write"} directive (isNeedWriteDirective)
// exists to prevent but cannot enforce.
//
// Reported twice by the reviewer, and confirmed against the stored transcript
// of PR 13451: on a plain edit request ("verander in 1 zin ...") the read-only
// first attempt answered "Ik heb deze beurt alsnog geen Edit/Bash, dus ik kan
// het niet zelf doorvoeren" plus the proposed replacement in a fence. That
// reply is internally consistent (attempt 1 genuinely has no Edit/Bash) but
// never triggers attempt 2, so the escalation the whole two-step design exists
// for silently never happens and the reviewer is left with a dead end. The
// same case was already addressed prompt-only (chat_readonly.md, "er is geen
// aparte goedkeurknop"), and recurred afterwards anyway — a model's adherence
// to that instruction is not something the prompt can guarantee, so
// runOneClaudeTurn escalates on this mechanically instead. Same shape as the
// natural-language stand-in for the checkout choice (chat_checkout.go): a
// short, explicit phrase list, not a general sentiment test.
//
// Deliberately NOT reviewer-facing: no button, key or palette command grants
// write access (reviewer decision, "zelf automatisch detecteren, dat hoeft de
// gebruiker niet te zien"). The only visible trace is the momentary
// chatPhaseEscalating progress line.
func looksLikeWriteRefusal(text string) bool {
	prose := strings.ToLower(stripCodeFencesForScan(text))
	for _, phrase := range writeRefusalPhrases {
		if strings.Contains(prose, phrase) {
			return true
		}
	}
	// "Edit en Bash zijn in deze sessie uitgeschakeld" — the second observed
	// wording, which names the tools and the absence in separate clauses, so
	// no single fragment above can catch it.
	if strings.Contains(prose, "uitgeschakeld") &&
		(strings.Contains(prose, "edit") || strings.Contains(prose, "bash") || strings.Contains(prose, "shell")) {
		return true
	}
	return false
}

// runOneClaudeTurn is the runClaudeTurn Activity's body (a plain function so
// it's directly testable): read the conversation's stored session id, ask
// claude for the next turn, persist the assistant's reply (parsed into a
// question turn when it matches the directive shape) plus the (possibly new)
// session id, and return the saved message. A failed claude call is stored as
// a visible turn rather than failing the workflow: chat.KindRetrying while
// runChatTurnWithRetries still has a rung left on its backoff ladder,
// chat.KindError once it is exhausted. The model is not fixed here either —
// chatModelForAttempt derives it from arg.Attempt.
//
// Task 3 ("een read-only vraag hoeft geen hele werkkopie op te bouwen"): every
// turn now makes up to TWO claude calls instead of committing upfront to full
// shell access.
//
//  1. A cheap first attempt with only Read/Grep/Glob, scoped to the PR's
//     already-ingested, SHARED head worktree (prepareChatReadOnlyWorkDir) — no
//     reviewer's own checkout, no git fetch, no ingestMu lock. This is enough for the
//     large majority of turns (explaining code, answering a question) and pays
//     none of the checkout-resolution cost.
//  2. ONLY when that first attempt's reply is the strict {"type":"need_write"}
//     directive (isNeedWriteDirective) — Claude's own signal that the
//     reviewer's request needs real edits/commands — a second call resumes the
//     SAME session with full Read/Grep/Glob/Edit/Bash in the conversation's own
//     PR's own shared local checkout (prepareChatShellWorkDir, now resolving from
//     before this task). That call's reply is what actually gets saved/parsed.
//
// Either attempt can fail to get its tools at all (gh/git unreachable, no
// worktree yet) — both degrade gracefully to a plain completion rather than an
// error turn, per .claude/rules/workflows-write-boundary.md's "Exception: the
// claude_chat turn may act through a shell". chat.Message.NoShell is true only
// when NEITHER attempt got any real tool access at all (see the "Geen
// bestandstoegang" pill, ClaudeChat.mjs) — a turn that only ever needed
// Read/Grep/Glob is not degraded, it simply never needed to escalate.
//
// A comment_action directive is deliberately NOT saved here as a message —
// applyChatCommentAction (called by the workflow right after this Activity,
// only when the returned action is non-nil) is the sole place that records the
// one visible outcome turn, so the reviewer only ever sees "it happened" or
// "it failed", never an optimistic message that turns out wrong.
func runOneClaudeTurn(ctx context.Context, tm *TaskManager, cm *chat.Module, cl claude.Client, dataDir string, arg chatTurnInput) (chat.Message, *commentActionDirective) {
	// Volatile live progress for the reviewer (chat_progress.go + the SSE
	// stream): a turn is a real subprocess call that can run for minutes, so
	// "Werkmap klaarzetten…"/"Claude start…" must be visible from the first
	// moment and grow with what the CLI streams back. None of it is persisted
	// or fed back into the Activity's result — see the OnEvent doc comment in
	// modules/claude.
	startChatProgress(arg.Repo, arg.PR, arg.ConversationID)
	defer finishChatProgress(arg.Repo, arg.PR, arg.ConversationID)

	// runCtx is the ONLY context that ever gets cancelled — by the reviewer's
	// own "Stop" (POST /api/chat/cancel → cancelChatTurn, chat_cancel.go), via
	// the CancelFunc registered here for the lifetime of this Activity. It is
	// used for every piece of OUTBOUND work this turn does (the claude CLI
	// subprocess, waiting for the write-turn slot, the git/gh checkout prep) —
	// never for persisting the turn's own outcome, which always uses the
	// ORIGINAL, uncancelled `ctx` tembed gave this Activity (context.Background(),
	// see tembed/workflow.go), so a message can still be saved after a cancel.
	// See chat_cancel.go's own doc comment for why a cancel cannot be a Signal.
	runCtx, cancel := context.WithCancel(ctx)
	unregister := registerChatCancel(arg.ConversationID, cancel)
	defer unregister()
	defer cancel()

	// t0/logTurnMilestone: a purely operational timing log (server.log), not
	// reviewer-facing and not persisted anywhere — same carve-out as
	// chat_progress.go itself. Exists so a slow turn (the claude CLI silently
	// retrying an API 529 overload can take minutes) can be diagnosed from the
	// log alone instead of only from a bug report of "it said the same thing
	// for 4 minutes".
	t0 := time.Now()
	logTurnMilestone := func(format string, args ...any) {
		if tm == nil || tm.logf == nil {
			return
		}
		tm.logf("claude_chat turn %s pr %d conv %s: "+format,
			append([]any{arg.TurnID, arg.PR, arg.ConversationID}, args...)...)
	}

	sessionID, _ := cm.GetSession(ctx, arg.ConversationID)

	// The work-directory choice is a PR-wide setting, answered in its own
	// overlay (chat_checkout.go, .claude/docs/command-palette.md) — never a
	// question inside a conversation. A turn's message is therefore always
	// ordinary review content; there is nothing to resolve here first.
	effectiveBody := arg.Body

	model := chatModelForAttempt(arg.Attempt)
	// checkoutDir starts empty (the read-only attempt below never edits
	// anything) and is set right before the shell attempt's own RunChat call,
	// once its WorkDir is known — see chatProgressSink's own doc comment.
	var checkoutDir string
	sink := chatProgressSink(arg.Repo, arg.PR, arg.ConversationID, &checkoutDir)
	loggedFirstEvent, loggedFirstContent := false, false
	onEvent := func(ev claude.ChatEvent) {
		if !loggedFirstEvent {
			loggedFirstEvent = true
			logTurnMilestone("first CLI event (%s) after %v", ev.Kind, time.Since(t0))
		}
		if !loggedFirstContent && ev.Kind != claude.ChatEventStatus {
			loggedFirstContent = true
			logTurnMilestone("first content event (%s) after %v", ev.Kind, time.Since(t0))
		}
		sink(ev)
	}

	// Attempt 1: the cheap read-only pass (task 3).
	hadReadOnly := false
	req := claude.RunRequest{
		Model:        model,
		Prompt:       buildChatPrompt(arg.Context, effectiveBody),
		SessionID:    sessionID,
		SystemPrompt: claude.ChatSystemPrompt,
		OnEvent:      onEvent,
	}
	if dir, ok := prepareChatReadOnlyWorkDir(dataDir, arg.Repo, arg.PR); ok {
		hadReadOnly = true
		req.WorkDir = dir
		req.Tools = []string{"Read", "Grep", "Glob"}
		req.SystemPrompt = claude.ChatReadOnlySystemPrompt
	}
	req.SystemPrompt += chatCommentIDNote(arg.ConversationID) + chatLangTail(langFor(ctx, tm, langpref.KindReply))
	// From here until RunChat returns, a reviewer message typed meanwhile can
	// still reach THIS call (chat_steer.go). Deliberately opened per CLI call,
	// not per turn: outside a live call there is nothing to hand it to, and the
	// chat_steer workflow then falls back to an ordinary next turn.
	steerCh, unregisterSteer := openSteerSlot(runCtx, arg.ConversationID)
	req.Steer = steerCh
	logTurnMilestone("local prep done after %v, invoking claude CLI (read-only attempt)", time.Since(t0))
	// Local prep is done; the CLI is about to be invoked. This is the "sessie
	// gestart — wachten op Claude" phase, kept distinct from the preceding
	// "Werkmap klaarzetten…" — see chatPhaseStarting/chatPhasePreparing in
	// chat_progress.go.
	advanceChatProgress(arg.Repo, arg.PR, arg.ConversationID, chatPhaseStarting)
	result, err := cl.RunChat(runCtx, req)
	unregisterSteer()
	logTurnMilestone("claude CLI (read-only attempt) returned after %v (err=%v)", time.Since(t0), err)
	if err != nil {
		// Checked via runCtx.Err(), never via error-value inspection: exec's own
		// killed-process error ("signal: killed") does not itself wrap
		// context.Canceled, so the only reliable signal that THIS was a
		// deliberate stop (rather than a genuine CLI/process failure) is the
		// context this Activity itself cancelled. Nothing was editable yet at
		// this read-only stage, so there is never a checkout to offer stashing.
		if runCtx.Err() != nil {
			return chatCancelledMessage(ctx, cm, arg, model), nil
		}
		return chatFailureMessage(ctx, cm, arg, model, err), nil
	}
	if err := cm.SetSession(ctx, arg.ConversationID, result.SessionID); err != nil {
		// Best-effort: losing the session id only means the NEXT call/turn starts
		// a fresh session instead of resuming this one — degraded, not broken.
		_ = err
	}

	// Attempt 2 (task 1/2/3): only when Claude itself asked for it — resumes
	// the SAME session, so it keeps whatever it already learned above, plus the
	// reviewer's own original message (already in that session's history).
	hadShell := false
	// Escalate on Claude's own strict directive OR on the prose it sometimes
	// falls back to instead (looksLikeWriteRefusal) — the reviewer never has
	// to ask twice for write access, and never gets a button for it either.
	escalate := isNeedWriteDirective(result.Text)
	if !escalate && looksLikeWriteRefusal(result.Text) {
		escalate = true
		logTurnMilestone("read-only attempt refused to write in prose after %v, escalating anyway", time.Since(t0))
		// The one visible trace of this: a momentary status line, no bubble
		// and no stored message (see looksLikeWriteRefusal's doc comment).
		advanceChatProgress(arg.Repo, arg.PR, arg.ConversationID, chatPhaseEscalating)
	}
	if escalate {
		// From here on this turn is going to CHANGE code, and only one such
		// turn runs at a time (chat_write_gate.go) — a second one waits here
		// instead of being refused. Everything above this line (the read-only
		// attempt that answers the large majority of turns) stays unlimited
		// and fully parallel across conversations.
		waited := false
		release := acquireWriteTurnSlot(runCtx, func() {
			waited = true
			logTurnMilestone("waiting for the code-turn slot after %v", time.Since(t0))
			advanceChatProgress(arg.Repo, arg.PR, arg.ConversationID, chatPhaseWaiting)
		})
		defer release()
		// A cancel that arrived while still WAITING for the slot never got to
		// touch the checkout at all — nothing to offer stashing.
		if runCtx.Err() != nil {
			return chatCancelledMessage(ctx, cm, arg, model), nil
		}
		if waited {
			// The wait is over; don't leave "Wacht op…" standing until the
			// first streamed event happens to replace it.
			logTurnMilestone("got the code-turn slot after %v", time.Since(t0))
			advanceChatProgress(arg.Repo, arg.PR, arg.ConversationID, chatPhaseStarting)
		}
		// reviewerReply is deliberately "" — see prepareChatShellWorkDir's own
		// doc comment: a chat message is never an answer to the
		// work-directory choice.
		dir, _, ok := prepareChatShellWorkDir(runCtx, tm, dataDir, arg.Repo, arg.PR, "")
		// A cancel can also land WHILE prepareChatShellWorkDir is resolving the
		// work directory (a git fetch/checkout/clean can take a moment) — check
		// before interpreting `ok`, which a cancelled context can otherwise
		// make look like an ordinary "no directory available" failure.
		if runCtx.Err() != nil {
			return chatCancelledMessage(ctx, cm, arg, model), nil
		}
		if !ok {
			// Two different dead ends, and they need different words. An open
			// work-directory choice is something the reviewer can resolve
			// right now (the overlay opens on it by itself, see
			// .claude/docs/command-palette.md); a missing checkout needs a
			// path in settings.json. Saying the latter while the former is
			// true sent the reviewer looking for a configuration problem that
			// wasn't there.
			body := "Voor dit verzoek heb ik schrijftoegang tot een lokale werkmap nodig, maar die is er niet. Voeg een pad toe aan `chatCheckoutDirs` in settings.json of clone de repo lokaal, en vraag het opnieuw."
			// A dead end with a KNOWN cause says that cause instead — the
			// checkout may well exist and simply not be readable/free right
			// now (see checkoutDiscovery.reason, chat_checkout.go).
			if reason := checkoutFailureReason(dataDir, arg.Repo, arg.PR); reason != "" {
				body = "Ik kan nu geen code aanpassen. " + reason + " Los dat op en vraag het opnieuw."
			}
			if checkoutChoiceOpen(dataDir, arg.Repo, arg.PR) {
				body = "Ik kan nu geen code aanpassen: er staat nog een keuze open over de werkmap van deze PR. Maak die keuze en vraag het daarna opnieuw."
			}
			msg := chat.Message{
				ID: chatMessageID(arg.TurnID, ""), ConversationID: arg.ConversationID, PR: arg.PR,
				Role: "assistant", Model: model, NoShell: true,
				Body: body,
			}
			_ = cm.SaveMessage(ctx, msg)
			return msg, nil
		}
		hadShell = true
		checkoutDir = dir // so an Edit/Write tool event below records a repo-relative path
		// Snapshot the checkout as it is RIGHT NOW, before Claude gets to
		// touch it — the automatic landing after this turn is allowed to run
		// only if this turn itself changed something (see
		// turnChangedCheckout, chat_checkout.go). A read-only turn never gets
		// here and therefore never lands anything.
		recordTurnCheckoutBaseline(runCtx, arg.ConversationID, dir)
		// Attempt 1's own streamed answer — often literally the strict
		// {"type":"need_write"} directive text itself, since that IS what it
		// answers when escalating — is still sitting in the live progress
		// snapshot's Partial field (chatProgressSink accumulates it exactly
		// like any other answer). Clear it before attempt 2 starts streaming
		// its own real, reviewer-facing text, or the two end up glued
		// together with no separator for the rest of the turn. See
		// resetChatProgressPartial's own doc comment.
		resetChatProgressPartial(arg.Repo, arg.PR, arg.ConversationID)
		shellReq := claude.RunRequest{
			Model:        model,
			Prompt:       chatNeedWriteContinuationPrompt,
			SessionID:    result.SessionID,
			SystemPrompt: claude.ChatShellSystemPrompt + chatCommentIDNote(arg.ConversationID) + chatLangTail(langFor(ctx, tm, langpref.KindReply)),
			WorkDir:      dir,
			Tools:        []string{"Read", "Grep", "Glob", "Edit", "Bash"},
			OnEvent:      onEvent,
		}
		shellSteerCh, unregisterShellSteer := openSteerSlot(runCtx, arg.ConversationID)
		shellReq.Steer = shellSteerCh
		logTurnMilestone("local prep done after %v, invoking claude CLI (shell attempt)", time.Since(t0))
		result2, err2 := cl.RunChat(runCtx, shellReq)
		unregisterShellSteer()
		logTurnMilestone("claude CLI (shell attempt) returned after %v (err=%v)", time.Since(t0), err2)
		if err2 != nil {
			if runCtx.Err() != nil {
				msg := chatCancelledMessage(ctx, cm, arg, model)
				// The CLI's OWN tool calls (Edit/Bash) may already have touched
				// `dir` before the kill reached it — offer to clean that up, but
				// ONLY when there really is something dirty (reviewer decision:
				// "alleen aanbieden als er echt iets is aangepast").
				offerCancelCleanupIfDirty(ctx, cm, arg, dir)
				return msg, nil
			}
			return chatFailureMessage(ctx, cm, arg, model, err2), nil
		}
		if err := cm.SetSession(ctx, arg.ConversationID, result2.SessionID); err != nil {
			_ = err
		}
		result = result2
		// Claude already got Edit/Bash on THIS very call, so a second
		// {"type":"need_write"} reply means it got stuck repeating the
		// escalation directive instead of acting on the write access it was
		// just granted — a degenerate model output, not the ordinary "needs
		// write access" signal any more. Without this, the raw directive JSON
		// fell through parseAssistantTurn's generic "unknown shape -> plain
		// text" default and the reviewer saw the literal
		// `{"type":"need_write"}` string as the bubble's body. This is
		// deliberately a PLAIN text turn (no Kind, no retry button) rather
		// than chat.KindError — nothing actually failed in the sense the
		// existing error/retry flow means (a CLI call that errored out or
		// exhausted its ladder); it is Claude's own answer, just a confusing
		// one, so it reads like an ordinary assistant notice the reviewer can
		// react to by simply typing again.
		if isNeedWriteDirective(result.Text) {
			msg := chat.Message{
				ID: chatMessageID(arg.TurnID, ""), ConversationID: arg.ConversationID, PR: arg.PR,
				Role: "assistant", Model: model,
				Body: "Claude had schrijftoegang, maar kwam er niet uit. Formuleer je verzoek iets concreter.",
			}
			_ = cm.SaveMessage(ctx, msg)
			return msg, nil
		}
	}

	msg, action := parseAssistantTurn(arg.PR, arg.ConversationID, arg.TurnID, result.Text)
	// Which model actually answered — the reviewer sees it on the bubble when it
	// isn't the default one (see the model pill in ClaudeChat.mjs).
	msg.Model = model
	// Whether this turn had NO real tool access AT ALL — surfaced via the "Geen
	// bestandstoegang" pill (ClaudeChat.mjs) so a silently degraded turn is
	// never invisible to the reviewer. False as soon as EITHER attempt got real
	// access (a read-only-only turn is not degraded — it simply never asked to
	// escalate). See prepareChatReadOnlyWorkDir/prepareChatShellWorkDir's own
	// doc comments for why either can legitimately fail.
	msg.NoShell = !(hadReadOnly || hadShell)
	// A pure directive turn has no visible message of its own (applyChatCommentAction
	// records its outcome instead), but a COMBINED turn — prose plus a trailing
	// comment_action, see parseAssistantTurn — does: the reviewer gets both the
	// explanation of what changed and the drafted reply.
	if action == nil || strings.TrimSpace(msg.Body) != "" {
		_ = cm.SaveMessage(ctx, msg)
	}
	return msg, action
}

// chatFailureTurn words one failed attempt for the reviewer and says, through
// its Kind, whether the workflow will try again by itself.
//
// KindRetrying while there is a next rung on the ladder ("nieuwe poging over N
// seconden"), KindError once it is exhausted — at which point only the manual
// "Opnieuw proberen" (chatActionRetry) starts it over. The wording names the
// model of the attempt that failed and of the next one, because a switch from
// Opus to Sonnet is exactly the kind of thing a reviewer should not have to
// guess at; the meaning lives in those words, never in the bubble's colour
// (the colourblind rule).
//
// callErr's Reason (claude.ChatCallError, see its doc comment) — the CLI's
// OWN explanation of what went wrong, e.g. an account usage limit or a
// billing problem — replaces the generic "Er ging iets mis" wording whenever
// available, so the reviewer sees the real cause instead of a made-up one.
// When that Reason is Definitive (the CLI completed the turn and judged it a
// failure itself, rather than a bare process/exec hiccup on our end) the
// ladder is stopped immediately: an automatic retry a few seconds later is
// very unlikely to change a verdict the CLI already reached on its own — a
// usage limit in particular normally resets hours later, not seconds — so
// promising a countdown here would be misleading. A callErr with no
// Definitive Reason (or a plain error, e.g. from existing tests) falls
// through to the unchanged ladder behaviour below.
func chatFailureTurn(attempt int, model string, callErr error) (kind, body string) {
	total := len(chatRetryDelays) + 1
	failed := fmt.Sprintf("Er ging iets mis bij het praten met Claude (%s). Poging %d van %d mislukt",
		chatModelLabel(model), attempt+1, total)

	var cce *claude.ChatCallError
	if errors.As(callErr, &cce) && cce.Reason != "" {
		failed = fmt.Sprintf("Claude (%s) meldde zelf een fout: %s", chatModelLabel(model), cce.Reason)
		if cce.Definitive {
			return chat.KindError, failed + " Dit lost een automatische nieuwe poging vermoedelijk niet op — probeer het straks handmatig opnieuw."
		}
	}

	if attempt >= len(chatRetryDelays) {
		return chat.KindError, failed + " — dat was de laatste automatische poging. Probeer het handmatig opnieuw."
	}
	next := chatModelForAttempt(attempt + 1)
	return chat.KindRetrying, fmt.Sprintf("%s — nieuwe poging over %d seconden met %s.",
		failed, int(chatRetryDelays[attempt].Seconds()), chatModelLabel(next))
}

// chatProgressThrottle bounds how often a text delta is pushed to the browser.
// The CLI streams a frame per token; forwarding every one of them would be a
// pointless SSE frame storm for something the reviewer reads at human speed.
// A phase/tool change always publishes immediately — that is exactly the
// "what is Claude doing now" signal, and it must never lag behind.
const chatProgressThrottle = 120 * time.Millisecond

// chatProgressSink builds the OnEvent callback that maps modules/claude's
// streamed ChatEvents onto the conversation's volatile progress snapshot and
// pushes it out. Called serially from RunChat's own single reader goroutine
// (see RunRequest.OnEvent), so the captured lastPublish needs no lock.
// chatProgressSink builds the OnEvent callback that maps modules/claude's
// streamed ChatEvents onto the conversation's volatile progress snapshot and
// pushes it out. checkoutDir is a pointer the CALLER updates once the shell
// attempt's own working directory is resolved (see runOneClaudeTurn) — it
// starts empty (the read-only attempt never edits anything) and is read here
// only to turn an Edit/Write tool's absolute file_path into the repo-relative
// path EditedFiles/the "wordt aangepast" pill actually compares against.
func chatProgressSink(repo string, pr int, conversationID string, checkoutDir *string) func(claude.ChatEvent) {
	var lastPublish time.Time
	return func(ev claude.ChatEvent) {
		snap, ok := mutateChatProgress(conversationID, func(p *chatProgress) {
			switch ev.Kind {
			case claude.ChatEventStatus:
				p.Phase = chatPhaseStarting
			case claude.ChatEventThinking:
				p.Phase = chatPhaseThinking
				p.Tool, p.Detail = "", ""
			case claude.ChatEventTool:
				p.Phase = chatPhaseTool
				p.Tool = ev.Tool
				// A tool block is announced twice (name first, arguments once they
				// have streamed in); never let the second, richer Detail be wiped
				// by the first announcement of the same tool.
				if ev.Detail != "" {
					p.Detail = ev.Detail
				}
				if (ev.Tool == "Edit" || ev.Tool == "Write") && ev.Detail != "" {
					addEditedFile(p, relativeToCheckout(*checkoutDir, ev.Detail))
				}
			case claude.ChatEventText:
				// A tool/thinking block in between means this delta starts a
				// BRAND NEW text content block (modules/claude/claude.go
				// fires a fresh content_block_start per block) — the model
				// never adds its own leading space/newline across that gap,
				// so naively appending glues the previous segment's last
				// word straight onto this one's first ("...toevoegen.Nu de
				// Unleash-config..."). A blank line separates them into
				// their own paragraphs once rendered as markdown
				// (claudePartialBubble, src/ClaudeChat.mjs).
				if p.Phase != chatPhaseWriting && p.Partial != "" {
					p.Partial += "\n\n"
				}
				p.Phase = chatPhaseWriting
				p.Tool, p.Detail = "", ""
				p.Partial += ev.TextDelta
			}
		})
		if !ok {
			return // the turn already finished; a late frame changes nothing
		}
		if ev.Kind == claude.ChatEventText && time.Since(lastPublish) < chatProgressThrottle {
			return
		}
		lastPublish = time.Now()
		publishChatProgress(repo, pr, conversationID, snap)
	}
}

// addEditedFile appends path to p.EditedFiles, skipping an already-present
// or empty path — a turn commonly re-opens the same file across several
// Edit calls, and the "wordt aangepast" pill only needs to know WHICH files,
// not how many times each was touched.
func addEditedFile(p *chatProgress, path string) {
	if path == "" {
		return
	}
	for _, f := range p.EditedFiles {
		if f == path {
			return
		}
	}
	p.EditedFiles = append(p.EditedFiles, path)
}

// relativeToCheckout turns an Edit/Write tool's absolute file_path (Claude's
// own working directory is the checkout itself, see prepareChatShellWorkDir)
// into the repo-relative path a block's own File field uses. Falls back to
// the raw path unchanged when dir is still empty (checkoutDir not resolved
// yet — never true for a real Edit/Write event, which can only ever fire
// once the shell attempt's WorkDir is set) or when path doesn't actually sit
// under dir (defensive; should not happen in practice).
func relativeToCheckout(dir, path string) string {
	if dir == "" {
		return path
	}
	rel, err := filepath.Rel(dir, path)
	if err != nil || strings.HasPrefix(rel, "..") {
		return path
	}
	return rel
}

// parseAssistantTurn turns the model's raw text into a chat.Message: a
// KindQuestion turn when the text is exactly the strict "question"
// assistantDirective JSON, a (nil chat.Message, non-nil directive) pair when
// it is a validated "comment_action" directive, otherwise a plain text turn
// (the raw text verbatim — including when it happens to start with "{" but
// doesn't parse as a recognized directive, so a stray/malformed directive
// degrades to plain text rather than vanishing), and a (text message,
// directive) PAIR when the answer is prose that ENDS with a comment_action
// directive on its own last line — one reviewer message may ask for both a
// code change and a reply on the comment thread.
// stripEmDash replaces every em dash ("—") with a plain hyphen. Used only on a
// comment_action "reply" body (see parseAssistantTurn) — the reviewer never
// wants that character in a Claude-drafted comment reply, and a system-prompt
// instruction alone isn't a guarantee.
func stripEmDash(s string) string {
	return strings.ReplaceAll(s, "—", "-")
}

func parseAssistantTurn(pr int, conversationID, turnID, text string) (chat.Message, *commentActionDirective) {
	msg := chat.Message{
		ID: chatMessageID(turnID, ""), ConversationID: conversationID, PR: pr,
		Role: "assistant", Body: text,
	}
	trimmed := strings.TrimSpace(text)
	if strings.HasPrefix(trimmed, "{") {
		var d assistantDirective
		if err := json.Unmarshal([]byte(trimmed), &d); err == nil {
			switch d.Type {
			case "question":
				if strings.TrimSpace(d.Question) == "" {
					return msg, nil
				}
				opts := d.Options
				if len(opts) > maxChatQuestionOptions {
					opts = opts[:maxChatQuestionOptions]
				}
				msg.Kind = chat.KindQuestion
				msg.Body = d.Question
				msg.Options = opts
				return msg, nil
			case "comment_action":
				if action := validateCommentAction(d); action != nil {
					return chat.Message{}, action
				}
			}
			// Unknown/malformed directive -> plain text, per the rule above.
			return msg, nil
		}
	}
	// A combined answer: ordinary prose (what Claude just changed) with the
	// comment_action directive on its own last line. This is what lets ONE
	// reviewer message ask for both a code change and a reply on the comment
	// thread — see "One message may ask for both" in
	// .claude/docs/workflows-comments.md.
	if prose, d := splitTrailingCommentAction(text); d != nil && strings.TrimSpace(prose) != "" {
		if action := validateCommentAction(*d); action != nil {
			msg.Body = prose
			return msg, action
		}
	}
	return msg, nil
}

// validateCommentAction turns a parsed "comment_action" directive into the
// applicable form, or nil when it fails any of the checks (unknown action, an
// empty reply body, no comment id) — the caller then degrades the whole turn
// to plain text rather than letting a malformed directive vanish.
func validateCommentAction(d assistantDirective) *commentActionDirective {
	if d.Action != "reply" && d.Action != "resolve" {
		return nil
	}
	if d.Action == "reply" && strings.TrimSpace(d.Body) == "" {
		return nil
	}
	if strings.TrimSpace(d.CommentID) == "" {
		return nil
	}
	body := d.Body
	if d.Action == "reply" {
		// The reviewer never wants an em dash in a Claude-drafted reply — this
		// body lands verbatim in the comment composer via saveChatDraftReply, so
		// sanitize it once here rather than trust the system prompt's wording
		// alone. "resolve" carries no reviewable body (always "/resolve", set by
		// applyChatCommentAction), so it needs no sanitizing.
		body = stripEmDash(body)
	}
	return &commentActionDirective{CommentID: d.CommentID, Action: d.Action, Body: body}
}

// splitTrailingCommentAction splits an answer that ENDS with a comment_action
// directive on its own last line into the prose before it and that directive.
// Blank lines and a stray markdown fence around the directive are tolerated
// (the system prompt asks for a bare line, but a fence is the one deviation
// models reach for); anything else returns the text unchanged and a nil
// directive.
func splitTrailingCommentAction(text string) (string, *assistantDirective) {
	lines := strings.Split(text, "\n")
	i := len(lines) - 1
	for i >= 0 {
		l := strings.TrimSpace(lines[i])
		if l != "" && l != "```" {
			break
		}
		i--
	}
	if i < 0 {
		return text, nil
	}
	var d assistantDirective
	if err := json.Unmarshal([]byte(strings.TrimSpace(lines[i])), &d); err != nil || d.Type != "comment_action" {
		return text, nil
	}
	prose := lines[:i]
	// Drop the fence opener the directive line sat inside, if there was one.
	for len(prose) > 0 {
		l := strings.TrimSpace(prose[len(prose)-1])
		if l == "" || strings.HasPrefix(l, "```") {
			prose = prose[:len(prose)-1]
			continue
		}
		break
	}
	return strings.TrimSpace(strings.Join(prose, "\n")), &d
}

// applyChatCommentAction is the applyChatCommentAction Activity's body (a
// plain, testable function, mirroring runOneClaudeTurn): validates a
// comment_action directive and, only if it passes every check, applies it.
//
// The two actions diverge on purpose (reviewer's explicit request): "resolve"
// still signals the target comment thread's own task_code_comment Execution
// directly via the EXISTING "reply" Signal (Source "ai") — never a direct
// write, the same sanctioned path an AI code_warning finding already uses —
// because there is no text to review first. "reply" does NOT touch the
// comment thread at all any more; Claude may draft a reply "on the reviewer's
// behalf", but only the reviewer's own edit + explicit send in the comment
// composer ever posts it (see saveChatDraftReply and, on the frontend,
// RelatedPanel.mjs's applyPendingDraftReplies). Every failure is also logged
// via tm.logf, per .claude/rules/workflows-write-boundary.md's best-effort
// convention — never a Go error that would fail the whole workflow.
func applyChatCommentAction(ctx context.Context, tm *TaskManager, arg chatCommentActionInput) {
	d := arg.Directive

	// The directive must target the conversation's OWN thread — a chat has no
	// context about any other comment of the PR, so any other id can only be a
	// hallucination/mistake, never a legitimate cross-thread request. Rejected
	// silently from the reviewer's point of view except for the log line + the
	// KindError turn below; never signalled, never drafted.
	if d.CommentID != arg.ConversationID {
		tm.logf("claude_chat: comment_action ignored — directive commentId=%q does not match conversation=%q (pr=%d)",
			d.CommentID, arg.ConversationID, arg.PR)
		saveChatActionOutcome(ctx, tm.chat, arg, "Kon niet worden toegepast — ongeldige comment-referentie.")
		return
	}
	if d.Action != "reply" && d.Action != "resolve" {
		tm.logf("claude_chat: comment_action ignored — unknown action=%q (pr=%d conversation=%s)", d.Action, arg.PR, arg.ConversationID)
		saveChatActionOutcome(ctx, tm.chat, arg, "Kon niet worden toegepast — onbekende actie.")
		return
	}
	if tm.comments == nil {
		saveChatActionOutcome(ctx, tm.chat, arg, "De comment-thread is niet beschikbaar.")
		return
	}
	c, ok, err := tm.comments.Get(ctx, arg.ConversationID)
	if err != nil || !ok || c.Status == "deleting" || c.Status == "deleted" {
		tm.logf("claude_chat: comment_action skipped — comment %s not found/deleted (pr=%d, err=%v)", arg.ConversationID, arg.PR, err)
		saveChatActionOutcome(ctx, tm.chat, arg, "De comment-thread bestaat niet meer.")
		return
	}

	if d.Action == "reply" {
		// No Signal, no Execution-status check: a draft is never written to the
		// comment thread by itself, so whether that thread's Execution can still
		// receive a Signal is irrelevant here — only the comment row itself must
		// still exist (checked above).
		saveChatDraftReply(ctx, tm.chat, arg, d.Body)
		return
	}

	// d.Action == "resolve" — an immediate action, no text to review first.
	// A completed/failed Execution can no longer receive a Signal — check
	// BEFORE signalling rather than relying on Signal's own error, so the
	// reviewer-facing message can name the real reason (mirrors the avatar-
	// backfill glue's own Status check in comment_import.go).
	status, err := tm.engine.Status(c.RunID)
	if err != nil || status == tembed.StatusCompleted || status == tembed.StatusFailed {
		tm.logf("claude_chat: comment_action skipped — thread %s not signallable (status=%q, err=%v)", c.RunID, status, err)
		saveChatActionOutcome(ctx, tm.chat, arg, "De comment-thread kan niet meer worden bijgewerkt.")
		return
	}

	// A deterministic reaction id for the same reason chatMessageID exists: a
	// replayed Activity must not post the SAME reply into the comment thread
	// twice (comments.AddReaction is an INSERT OR IGNORE on this id).
	sig := ReactionSignal{ID: chatActionReactionID(arg.TurnID), Source: "ai", Author: "Claude", Body: resolveSentinel, Done: true}
	if err := tm.Signal(c.RunID, sig); err != nil {
		tm.logf("claude_chat: comment_action signal failed for %s: %v", c.RunID, err)
		saveChatActionOutcome(ctx, tm.chat, arg, "Kon de comment-thread niet bijwerken. Probeer het opnieuw.")
		return
	}
	saveChatActionOutcome(ctx, tm.chat, arg, "✓ Comment-thread opgelost.")
}

// saveChatActionOutcome records the single visible turn for a comment_action
// "resolve" attempt (or a validation failure of either action): KindAction for
// a text starting with "✓" (the success text built above), KindError for
// anything else — see chat.KindAction's own doc comment.
func saveChatActionOutcome(ctx context.Context, cm *chat.Module, arg chatCommentActionInput, text string) {
	if cm == nil {
		return
	}
	kind := chat.KindError
	if strings.HasPrefix(text, "✓") {
		kind = chat.KindAction
	}
	_ = cm.SaveMessage(ctx, chat.Message{
		ID: chatMessageID(arg.TurnID, "action"), ConversationID: arg.ConversationID, PR: arg.PR,
		Role: "assistant", Kind: kind, Body: text,
	})
}

// saveChatDraftReply records a comment_action "reply" directive's drafted
// body as its own turn (chat.KindDraftReply) — never signalled onto the
// comment thread. A distinct id suffix ("draft") from saveChatActionOutcome's
// ("action") so the two can never collide for the same TurnID; deterministic
// under replay for the same reason chatMessageID exists (modules/chat.SaveMessage
// is an INSERT OR REPLACE on this id).
func saveChatDraftReply(ctx context.Context, cm *chat.Module, arg chatCommentActionInput, body string) {
	if cm == nil {
		return
	}
	_ = cm.SaveMessage(ctx, chat.Message{
		ID: chatMessageID(arg.TurnID, "draft"), ConversationID: arg.ConversationID, PR: arg.PR,
		Role: "assistant", Kind: chat.KindDraftReply, Body: body,
	})
}
