// chat_workflow.go — the claude_chat workflow: an embedded, multi-turn Claude
// conversation next to one existing review comment thread (see
// .claude/docs/tembed-workflows.md). One Execution per conversation; its
// Run ID is derived from the comment thread's own id, so starting it twice
// for the same comment is an idempotent no-op (StartWorkflowID) and the
// frontend never has to remember a separate chat Run ID of its own.
package main

import (
	"context"
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"github.com/reindert-vetter/tembed"
	"slash/modules/chat"
	"slash/modules/claude"
)

// ClaudeChatInput starts (or, idempotently, re-ensures) a claude_chat
// Workflow Execution. CommentID is the existing task_code_comment thread this
// conversation hangs on — per product decision, a chat is always attached to
// an EXISTING comment thread and is normally a child workflow of it (see
// StartClaudeChat). Nothing auto-creates a comment for it: no comment (and no
// earlier conversation) means no chat, so the reviewer never gets a placeholder
// comment they didn't ask for.
type ClaudeChatInput struct {
	PR        int    `json:"pr"`
	CommentID string `json:"commentId"`
}

// ChatMessageSignal is the payload of a "message" Signal — one reviewer turn.
// ID is generated by the HTTP handler (like ReactionSignal.ID for a UI
// reaction), not inside the workflow body, so it stays deterministic under
// replay.
//
// Action rides along as a variant of this one Signal (mirrors
// ReactionSignal.Action, which the task_code_comment workflow already uses
// for "delete") — tembed can only WaitSignal on one name at a time, so a
// second signal name isn't an option. "" is the ordinary turn: runOneClaudeTurn
// itself already tries to get Claude real shell/file access in the
// conversation's own shadow worktree (chat_shadow.go/prepareChatShellWorkDir)
// for EVERY turn, degrading silently to a tool-less completion when git/gh is
// unreachable — see that function's doc comment. chatActionEdit is kept only
// as a backward-compatible no-op synonym of ""; chatActionCommit
// fast-forward-pushes the shadow's edits onto the PR's real head branch and
// needs no Body at all (still the one dedicated path for that, alongside
// Claude's own Bash access being able to do the same on request).
//
// Context is the reviewer's selection at the time they sent this turn — file,
// old/new line range, a code excerpt (built client-side by RelatedPanel.mjs,
// only for a conversation's very first turn — see claude-chat-panel.md) — and
// is deliberately NEVER saved as part of the visible chat.Message.Body: it
// only enriches the PROMPT sent to the claude CLI (see runOneClaudeTurn's
// buildChatPrompt). The reviewer's own bubble must show exactly what they
// typed, nothing more.
type ChatMessageSignal struct {
	ID      string `json:"id"`
	Author  string `json:"author"`
	Body    string `json:"body"`
	Action  string `json:"action,omitempty"`
	Context string `json:"context,omitempty"`
}

// The three non-default ChatMessageSignal.Action values. Validated by the HTTP
// handler (tasks_api.go) before the Signal is ever sent — an unrecognized
// value is rejected there, so the workflow body only ever sees one of these
// four, and the branch it takes is thus fully determined by the Signal's own
// input (workflow-determinism.md).
const (
	chatActionEdit   = "edit"   // no-op synonym of "" — every turn already gets shell/Edit access
	chatActionCommit = "commit" // commit + push the shadow worktree's edits
	// chatActionClear is "wis gesprek" (the palette's confirm-gated command,
	// see rootCommandsFor('claude') in home.mjs): wipe the transcript + the
	// stored claude session, and best-effort remove the conversation's own
	// agentic-edit shadow worktree (chat_shadow.go's clearChatShadow). The
	// reviewer already saw a warning about any pending (uncommitted/unpushed)
	// shadow work before confirming — see the read-only
	// GET /api/chat/shadow-status endpoint (tasks_api.go) and
	// chatShadowPendingWarning (RelatedPanel.mjs) — so this proceeds
	// unconditionally once the Signal arrives.
	chatActionClear = "clear"
	// chatActionRetry re-runs the LAST turn that finally failed (the automatic
	// backoff ladder below gave up on it), reusing that turn's own input —
	// same TurnID, same Body, same Context — so the failed bubble is replaced
	// rather than joined by a second copy of the reviewer's message. Carries no
	// Body of its own, like "commit"/"clear". A no-op when nothing failed.
	chatActionRetry = "retry"
)

// chatRetryDelays is the automatic backoff ladder for a failed Claude call:
// the wait AFTER attempt i, so len(chatRetryDelays)+1 attempts in total (~93s
// of waiting). A var, not a const slice, purely so a test can shrink it —
// nothing else ever writes it.
//
// The waiting itself happens through w.Sleep (a durable timer that survives a
// restart), never a wall-clock sleep inside the workflow body, and the index
// is the loop counter — so which delay is used follows from the recorded
// history alone (.claude/rules/workflow-determinism.md).
var chatRetryDelays = []time.Duration{
	3 * time.Second,
	6 * time.Second,
	12 * time.Second,
	24 * time.Second,
	48 * time.Second,
}

// chatModelForAttempt picks the model for one attempt of a chat turn: Opus
// first, Sonnet from the third attempt on.
//
// Why not switch on the FIRST retry: the common failure here is a short
// capacity blip (an overloaded/aborted stream), which is usually gone after
// three seconds — and the reviewer picked this panel for Opus-quality answers,
// so a one-off hiccup should not cost that. Why switch at all: if TWO Opus
// attempts three seconds apart both fail, it is not a moment but a sustained
// capacity/quota problem on that model, and another model is then a better bet
// than waiting even longer.
//
// Deliberately NOT sticky for the rest of the conversation: the next reviewer
// turn starts at attempt 0 again, hence at Opus. A temporary outage must not
// silently downgrade the whole conversation, and keeping the choice a pure
// function of the attempt counter is exactly what keeps it deterministic under
// replay — nothing about it is stored or read from outside the workflow. The
// CLI session is unaffected: the model is a per-invocation flag, --resume
// keeps the same transcript either way.
func chatModelForAttempt(attempt int) string {
	if attempt < 2 {
		return claude.ModelOpus
	}
	return claude.ModelSonnet
}

// chatModelLabel is the short, reviewer-facing name of a model id (mirrored by
// MODEL_LABEL in src/ClaudeChat.mjs). An unknown id is shown verbatim.
func chatModelLabel(model string) string {
	switch model {
	case claude.ModelOpus:
		return "Opus"
	case claude.ModelSonnet:
		return "Sonnet"
	case claude.ModelHaiku:
		return "Haiku"
	}
	return model
}

// chatConversationRunID derives the claude_chat Execution's Run ID from the
// comment thread it hangs on. The comment id is already a short, filename-safe
// random hex string (or "gh-<id>" for an imported thread — see ids.go/
// comment_import.go), so no hashing is needed here, unlike explainRunID/
// resolveCallRunID (whose keys embed file paths).
func chatConversationRunID(commentID string) string {
	return "chat-" + commentID
}

// StartClaudeChat ensures the claude_chat Execution for commentID exists and
// returns its Run ID — the sanctioned UI write path (starting/reusing an
// Execution). Idempotent either way, and the Run ID is the same
// chatConversationRunID(commentID) in both routes below, so callers (the UI's
// message Signal, chat_merge.go, cleanup.go) never see the difference.
//
// The conversation belongs to the comment thread, so it is started as a CHILD
// workflow of that thread's own task_code_comment Execution — via its existing
// "reply" Signal with Action "chat" (tembed can only WaitSignal on one name at
// a time, so this rides along like "avatar"/"reanchor"/"delete"). Signalling is
// synchronous (SignalWorkflow advances the run inline, which starts the child
// inline too), so by the time this returns the chat run exists and can be
// signalled itself.
//
// CARVE-OUT: taskCodeCommentWorkflow ENDS on a delete (and, before resolving
// became reversible, also on a resolve — threads resolved back then are still
// completed, see workflows-comments.md), and a completed
// Execution can no longer receive a Signal. A thread whose Execution is gone or
// unreachable must not lose its chat, so those cases fall back to the original
// top-level StartWorkflowID (the run then simply has no ParentRunID — exactly
// what every chat created before this change looks like). Same "check the
// status BEFORE signalling" shape as applyChatCommentAction below.
func (m *TaskManager) StartClaudeChat(in ClaudeChatInput) (string, error) {
	runID := chatConversationRunID(in.CommentID)
	parent, ok := m.commentThreadRunID(in)
	if ok {
		err := m.Signal(parent, ReactionSignal{Action: "chat"})
		if err == nil {
			return runID, nil
		}
		m.logf("claude_chat: chat signal to thread %s failed, starting top-level instead: %v", parent, err)
	}
	return m.engine.StartWorkflowID(runID, WorkflowClaudeChat, in)
}

// commentThreadRunID resolves the task_code_comment Run ID that can host
// in.CommentID's conversation as a child, reporting false when that thread is
// unknown or can no longer be signalled (see StartClaudeChat's carve-out).
func (m *TaskManager) commentThreadRunID(in ClaudeChatInput) (string, bool) {
	if m.comments == nil {
		return "", false
	}
	ctx := context.Background()
	c, found, err := m.comments.Get(ctx, in.CommentID)
	if err != nil || !found || c.RunID == "" {
		m.logf("claude_chat: comment %s has no signallable thread, starting chat top-level (found=%v, err=%v)", in.CommentID, found, err)
		return "", false
	}
	status, err := m.engine.Status(c.RunID)
	if err != nil || status == tembed.StatusCompleted || status == tembed.StatusFailed {
		m.logf("claude_chat: thread %s not signallable (status=%q, err=%v), starting chat top-level", c.RunID, status, err)
		return "", false
	}
	return c.RunID, true
}

// claudeChatWorkflow is the durable definition. Deterministic: the only side
// effects are ExecuteActivity calls, and the loop tracks "is the assistant
// waiting on an answer to a question turn" purely from the PREVIOUS Activity
// result (pendingQuestionID), never from wall-clock/random state — safe under
// replay. It never completes — a long-lived per-conversation tracker, mould
// of taskCodeCommentWorkflow's reactions loop.
func claudeChatWorkflow(w *tembed.Workflow, input []byte) ([]byte, error) {
	var in ClaudeChatInput
	if err := json.Unmarshal(input, &in); err != nil {
		return nil, err
	}
	if err := w.ExecuteActivity("ensureChatConversation", in, nil); err != nil {
		return nil, fmt.Errorf("ensure chat conversation: %w", err)
	}

	pendingQuestionID := ""
	// lastFailedTurn is the input of the turn whose automatic retry ladder ran
	// out, kept so a later chatActionRetry Signal can run exactly that turn
	// again. Reconstructed identically on every replay (it only ever holds
	// values that came from a recorded Signal), so it is as deterministic as
	// pendingQuestionID above.
	var lastFailedTurn *chatTurnInput
	for {
		var sig ChatMessageSignal
		w.WaitSignal(SignalMessage, &sig)

		// "wis gesprek": wipe the transcript + session (and best-effort the shadow
		// worktree) via one Activity, drop any pending question, and go straight
		// back to WaitSignal — no user/assistant text turn, no Claude call. Decided
		// purely by sig.Action, part of the Signal's own recorded input, so this is
		// deterministic under replay exactly like the chatActionCommit branch below.
		if sig.Action == chatActionClear {
			if err := w.ExecuteActivity("clearChatConversation", chatCommitInput{
				PR: in.PR, ConversationID: in.CommentID,
			}, nil); err != nil {
				return nil, fmt.Errorf("clear chat conversation: %w", err)
			}
			pendingQuestionID = ""
			lastFailedTurn = nil
			continue
		}

		// "commit deze wijziging": hand this conversation's shadow-worktree edits
		// to the PR's own chat_merge queue, which serializes every conversation's
		// commit request for this PR so two of them landing around the same time
		// are merged one after another instead of racing each other's
		// fast-forward-only push (see chat_merge.go). No Claude call and no
		// user/assistant text turn here — the eventual outcome message is
		// recorded by processChatMerge, on the queue's OWN Execution, once it
		// gets to this request. This branch is decided purely by sig.Action, part
		// of the Signal's own recorded input — deterministic under replay.
		if sig.Action == chatActionCommit {
			if err := w.ExecuteActivity("enqueueChatMerge", chatCommitInput{
				PR: in.PR, ConversationID: in.CommentID, TurnID: sig.ID,
			}, nil); err != nil {
				return nil, fmt.Errorf("enqueue chat merge: %w", err)
			}
			continue
		}

		// "Opnieuw proberen": re-run the turn whose automatic ladder ran out,
		// with its OWN recorded input — same TurnID, so its failed bubble is
		// replaced rather than joined by a second copy of the reviewer's
		// message — and no new user turn/answer bookkeeping. Nothing failed
		// (yet) means nothing to do. Decided purely by sig.Action plus
		// lastFailedTurn, which itself only ever holds recorded values.
		turn := chatTurnInput{
			PR: in.PR, ConversationID: in.CommentID, Body: sig.Body, Action: sig.Action, TurnID: sig.ID,
			Context: sig.Context,
		}
		if sig.Action == chatActionRetry {
			if lastFailedTurn == nil {
				continue
			}
			turn = *lastFailedTurn
		} else {
			// The reviewer's next message answers the assistant's last question turn,
			// if there was one still open.
			if pendingQuestionID != "" {
				if err := w.ExecuteActivity("saveChatAnswer", map[string]any{
					"id": pendingQuestionID, "answer": sig.Body,
				}, nil); err != nil {
					return nil, fmt.Errorf("save chat answer: %w", err)
				}
				pendingQuestionID = ""
			}

			if err := w.ExecuteActivity("saveChatMessage", chat.Message{
				ID: sig.ID, ConversationID: in.CommentID, PR: in.PR, Role: "user", Body: sig.Body,
			}, nil); err != nil {
				return nil, fmt.Errorf("save chat user message: %w", err)
			}
		}

		result, err := runChatTurnWithRetries(w, turn)
		if err != nil {
			return nil, err
		}
		// The ladder is exhausted: the turn stands as "mislukt" until the
		// reviewer asks for it again (chatActionRetry above). Its input is kept
		// verbatim so that retry is the very same turn.
		if result.Message.Kind == chat.KindError {
			failed := turn
			lastFailedTurn = &failed
			continue
		}
		lastFailedTurn = nil
		if result.Message.Kind == chat.KindQuestion {
			pendingQuestionID = result.Message.ID
		}

		// Phase 4: only when the reviewer explicitly asked for it, the assistant's
		// turn may carry a comment_action directive (parsed by parseAssistantTurn,
		// returned instead of a saved message by runOneClaudeTurn — see
		// chatTurnResult). Whether this Activity runs at all is decided purely by
		// the STORED result of the Activity just above (result.Action != nil),
		// mirroring the pendingQuestionID branch: deterministic under replay, never
		// dependent on live state. applyChatCommentAction is the only thing that
		// signals the comment thread's own task_code_comment Execution — via its
		// existing "reply" Signal (Source "ai"), never a direct write — and it also
		// records the one visible outcome turn (success or KindError).
		if result.Action != nil {
			if err := w.ExecuteActivity("applyChatCommentAction", chatCommentActionInput{
				PR: in.PR, ConversationID: in.CommentID, Directive: *result.Action, TurnID: turn.TurnID,
			}, nil); err != nil {
				return nil, fmt.Errorf("apply chat comment action: %w", err)
			}
		}
	}
}

// chatTurnInput is runClaudeTurn's own Activity input — deliberately not
// ClaudeChatInput + a DB read of the transcript: the CLI's own --resume
// session already carries prior turns, so only the new message body needs to
// travel along (it's already in the workflow's history via the Signal).
// Action mirrors ChatMessageSignal.Action — kept for chatActionCommit
// dispatch (handled by the workflow before runOneClaudeTurn is even called)
// and as a backward-compatible field; runOneClaudeTurn itself no longer
// branches on it (see that function's doc comment).
// TurnID is the reviewer Signal's own id (ChatMessageSignal.ID, generated by
// the HTTP handler and therefore part of the recorded history) — see
// chatMessageID for why every message this turn writes derives its id from it.
// Context mirrors ChatMessageSignal.Context — folded into the CLI prompt by
// buildChatPrompt, never into the saved chat.Message.Body.
// Attempt/MaxAttempts are the position in runChatTurnWithRetries' backoff
// ladder (0-based / total). They decide the model (chatModelForAttempt) and
// the wording of a failed attempt's bubble, and they come from the workflow's
// own loop counter, so both stay deterministic under replay.
type chatTurnInput struct {
	PR             int    `json:"pr"`
	ConversationID string `json:"conversationId"`
	Body           string `json:"body"`
	Action         string `json:"action,omitempty"`
	TurnID         string `json:"turnId,omitempty"`
	Context        string `json:"context,omitempty"`
	Attempt        int    `json:"attempt,omitempty"`
	MaxAttempts    int    `json:"maxAttempts,omitempty"`
}

// runChatTurnWithRetries drives one reviewer turn through the automatic
// backoff ladder: run it, and while the Activity reports a still-retryable
// failure (chat.KindRetrying), wait chatRetryDelays[attempt] on a DURABLE
// timer and run it again. It returns the final result — a normal/question
// turn, a comment_action directive, or a chat.KindError message meaning the
// ladder is exhausted.
//
// Deterministic: the number of iterations and the delay index follow only from
// the recorded Activity results and the loop counter, the wait is w.Sleep (a
// timer event in the history, rescheduled after a restart), and nothing reads
// a live clock. Every attempt reuses the same TurnID, so each one REPLACES the
// previous attempt's row instead of adding a bubble (see chatMessageID).
func runChatTurnWithRetries(w *tembed.Workflow, turn chatTurnInput) (chatTurnResult, error) {
	var result chatTurnResult
	for attempt := 0; ; attempt++ {
		arg := turn
		arg.Attempt = attempt
		arg.MaxAttempts = len(chatRetryDelays) + 1
		if err := w.ExecuteActivity("runClaudeTurn", arg, &result); err != nil {
			return result, fmt.Errorf("run claude turn: %w", err)
		}
		if result.Message.Kind != chat.KindRetrying {
			return result, nil
		}
		w.Sleep(chatRetryDelays[attempt])
	}
}

// chatCommitInput is commitChatShadowEdits's own Activity input (chat_shadow.go).
type chatCommitInput struct {
	PR             int    `json:"pr"`
	ConversationID string `json:"conversationId"`
	TurnID         string `json:"turnId,omitempty"`
}

// chatMessageID derives the id of an assistant message from the reviewer turn
// that caused it, so writing it twice overwrites one row instead of adding a
// second (modules/chat.SaveMessage is an INSERT OR REPLACE on this id).
//
// LOAD-BEARING for replay, not cosmetic: an Activity's side effects happen
// BEFORE its result is appended to the history, so a process killed in that
// window re-executes the whole Activity on recovery — with a random id that
// meant the reviewer ended up with two copies of the same assistant turn, one
// of them orphaned. turnId comes from the Signal (recorded input), so it is
// identical on every replay. `suffix` separates the two messages one turn can
// legitimately produce (the assistant's own reply, and a comment_action
// outcome). An empty turnId — an input recorded before this field existed —
// falls back to the old random id, which is exactly the previous behaviour.
func chatMessageID(turnID, suffix string) string {
	if turnID == "" {
		return "asst-" + newUIReactionID()
	}
	if suffix != "" {
		return "asst-" + turnID + "-" + suffix
	}
	return "asst-" + turnID
}

// chatActionReactionID is chatMessageID's counterpart for the ONE reaction a
// comment_action turn may post into the comment thread — same replay reasoning
// (comments.AddReaction is an INSERT OR IGNORE on this id, so a re-executed
// Activity re-posts nothing).
func chatActionReactionID(turnID string) string {
	if turnID == "" {
		return "sys-" + newUIReactionID()
	}
	return "sys-" + turnID + "-action"
}

// chatTurnResult is runClaudeTurn's own Activity return shape: the saved
// chat.Message (or, for a comment_action turn, a zero Message — see below)
// plus, only when the assistant's reply was a validated comment_action
// directive, the parsed action for the workflow to apply next via
// applyChatCommentAction. Kept separate from chat.Message itself (whose
// chat_messages persistence writes an explicit column list, never full-struct
// reflection — see modules/chat.SaveMessage) so this workflow-only handoff
// never leaks into modules/chat, which knows nothing about
// task_code_comment/ReactionSignal addressing.
type chatTurnResult struct {
	Message chat.Message            `json:"message"`
	Action  *commentActionDirective `json:"action,omitempty"`
}

// commentActionDirective is the parsed, but NOT YET validated, shape of a
// reviewer-requested {"type":"comment_action",...} assistant directive.
// CommentID is re-validated by applyChatCommentAction against the
// conversation's own thread before anything is signalled — see
// parseAssistantTurn and .claude/docs/workflows-comments.md ("claude_chat").
type commentActionDirective struct {
	CommentID string `json:"commentId"`
	Action    string `json:"action"` // "reply" | "resolve"
	Body      string `json:"body"`   // required for "reply", ignored for "resolve"
}

// chatCommentActionInput is applyChatCommentAction's own Activity input.
type chatCommentActionInput struct {
	PR             int                    `json:"pr"`
	ConversationID string                 `json:"conversationId"`
	Directive      commentActionDirective `json:"directive"`
	TurnID         string                 `json:"turnId,omitempty"`
}

// assistantDirective is the strict JSON shape claude.ChatSystemPrompt asks
// the model to use — a clarifying question with a few choices ("question"),
// or, only on the reviewer's explicit request, an action to apply to the left
// comment thread ("comment_action", Phase 4). Anything that doesn't parse as
// one of these two recognized shapes is treated as a plain text turn.
type assistantDirective struct {
	Type     string   `json:"type"` // "question" | "comment_action"
	Question string   `json:"question"`
	Options  []string `json:"options"`
	// The following three fields are comment_action-only.
	Action    string `json:"action"` // "reply" | "resolve"
	CommentID string `json:"commentId"`
	Body      string `json:"body"`
}

// maxChatQuestionOptions caps how many choices a question turn offers,
// per product decision ("max 3, met eigen input als vierde optie" — the
// reviewer can always type free text instead of picking one, so the UI never
// needs a real 4th option).
const maxChatQuestionOptions = 3

// runOneClaudeTurn is the runClaudeTurn Activity's body (a plain function so
// it's directly testable, mirroring resolveCallsWithModel/
// runCodeWarningReview): read the conversation's stored session id, ask
// claude for the next turn (resuming that session, or starting one), persist
// the assistant's reply (parsed into a question turn when it matches the
// directive shape) plus the (possibly new) session id, and return the saved
// message. A failed claude call is stored as a visible turn rather than
// failing the workflow: chat.KindRetrying while runChatTurnWithRetries still
// has a rung left on its backoff ladder (that Kind is precisely what tells the
// workflow to sleep and call this again), chat.KindError once it is exhausted.
// The model is not fixed here either — chatModelForAttempt derives it from
// arg.Attempt, so the third attempt onward runs on Sonnet.
//
// Every turn — regardless of arg.Action — first tries prepareChatShellWorkDir
// (chat_shadow.go) to get real shell/file access in the conversation's own
// disposable shadow worktree: Read/Grep/Glob/Edit plus Bash, so Claude can run
// git/gh/acli itself when the reviewer asks for it in plain text, per
// .claude/rules/workflows-write-boundary.md's "Exception: the Claude chat
// turn may act through a shell". That setup can fail (gh/git unreachable) —
// prepareChatShellWorkDir turns any such failure into "not available this
// turn" rather than an error, and the turn simply falls back to the original
// tool-less completion (claude.ChatSystemPrompt, no WorkDir/Tools) so a pure
// conversational turn never breaks because of it. See
// .claude/docs/claude-chat-panel.md and .claude/docs/workflows-comments.md.
//
// arg.Action == chatActionEdit is kept only for backward compatibility with
// any already-recorded history/external caller — it is now a no-op synonym of
// the default, since every turn already gets the same widened access. Do NOT
// reintroduce a gate on it; that was the exact mistake this comment exists to
// prevent (see the git history of this file for the broken attempt that made
// 'edit' the unconditional default and, with it, tied every turn to a live
// gh/git round trip with no fallback).
//
// A comment_action directive is deliberately NOT saved here as a message —
// applyChatCommentAction (called by the workflow right after this Activity,
// only when the returned action is non-nil) is the sole place that records the
// one visible outcome turn, so the reviewer only ever sees "it happened" or
// "it failed", never an optimistic message that turns out wrong.
// buildChatPrompt folds the reviewer's selection context (if any — only sent
// for a conversation's first turn, see RelatedPanel.mjs's claudeContextBlock)
// in FRONT of the typed message for the CLI's own Prompt, so Claude sees what
// file/line/code the reviewer is asking about. Deliberately never used for
// what gets SAVED as chat.Message.Body (see saveChatMessage in
// claudeChatWorkflow above) — the reviewer's own bubble must show only what
// they typed. context == "" (every turn after the first, or no cursor info
// available) is a plain pass-through, unchanged from before this field
// existed.
func buildChatPrompt(selectionContext, body string) string {
	if selectionContext == "" {
		return body
	}
	return selectionContext + "\n\n" + body
}

func runOneClaudeTurn(ctx context.Context, tm *TaskManager, cm *chat.Module, cl claude.Client, dataDir string, arg chatTurnInput) (chat.Message, *commentActionDirective) {
	// Volatile live progress for the reviewer (chat_progress.go + the SSE
	// stream): a turn is a real subprocess call that can run for minutes, so
	// "Werkmap klaarzetten…"/"Claude start…" must be visible from the first
	// moment and grow with what the CLI streams back. None of it is persisted
	// or fed back into the Activity's result — see the OnEvent doc comment in
	// modules/claude.
	startChatProgress(arg.PR, arg.ConversationID)
	defer finishChatProgress(arg.PR, arg.ConversationID)

	// t0/logTurnMilestone: a purely operational timing log (server.log), not
	// reviewer-facing and not persisted anywhere — same carve-out as
	// chat_progress.go itself. Exists so a slow turn (the claude CLI silently
	// retrying an API 529 overload can take minutes) can be diagnosed from the
	// log alone instead of only from a bug report of "it said the same thing
	// for 4 minutes".
	t0 := time.Now()
	logTurnMilestone := func(format string, args ...any) {
		if tm == nil || tm.logf == nil {
			return
		}
		tm.logf("claude_chat turn %s pr %d conv %s: "+format,
			append([]any{arg.TurnID, arg.PR, arg.ConversationID}, args...)...)
	}

	sessionID, _ := cm.GetSession(ctx, arg.ConversationID)
	model := chatModelForAttempt(arg.Attempt)
	sink := chatProgressSink(arg.PR, arg.ConversationID)
	loggedFirstEvent, loggedFirstContent := false, false
	req := claude.RunRequest{
		Model:        model,
		Prompt:       buildChatPrompt(arg.Context, arg.Body),
		SessionID:    sessionID,
		SystemPrompt: claude.ChatSystemPrompt,
		OnEvent: func(ev claude.ChatEvent) {
			if !loggedFirstEvent {
				loggedFirstEvent = true
				logTurnMilestone("first CLI event (%s) after %v", ev.Kind, time.Since(t0))
			}
			if !loggedFirstContent && ev.Kind != claude.ChatEventStatus {
				loggedFirstContent = true
				logTurnMilestone("first content event (%s) after %v", ev.Kind, time.Since(t0))
			}
			sink(ev)
		},
	}
	if dir, ok := prepareChatShellWorkDir(ctx, tm, dataDir, arg.PR, arg.ConversationID); ok {
		req.WorkDir = dir
		req.Tools = []string{"Read", "Grep", "Glob", "Edit", "Bash"}
		req.SystemPrompt = claude.ChatShellSystemPrompt
	}
	logTurnMilestone("local prep done after %v, invoking claude CLI", time.Since(t0))
	// The embedded prompt files are static, call-independent text (see
	// modules/claude/prompts.go), so the conversation's own comment id — which
	// chat.md's comment_action directive needs to echo back as "commentId" —
	// is appended here in Go, the same "static block + dynamic call-specific
	// content" split every other prompt already uses. Harmless for a turn that
	// never uses the directive.
	req.SystemPrompt += "\n\nHet id van DEZE comment-thread (gebruik dit exact als \"commentId\" in het comment_action-format): " + arg.ConversationID
	// Local prep (gh/git worktree refresh above) is done; the CLI is about to
	// be invoked. This is the "sessie gestart — wachten op Claude" phase, kept
	// distinct from the preceding "Werkmap klaarzetten…" — see chatPhaseStarting
	// / chatPhasePreparing in chat_progress.go.
	advanceChatProgress(arg.PR, arg.ConversationID, chatPhaseStarting)
	result, err := cl.RunChat(ctx, req)
	logTurnMilestone("claude CLI returned after %v (err=%v)", time.Since(t0), err)
	if err != nil {
		kind, body := chatFailureTurn(arg.Attempt, model)
		msg := chat.Message{
			ID: chatMessageID(arg.TurnID, ""), ConversationID: arg.ConversationID, PR: arg.PR,
			Role: "assistant", Kind: kind, Body: body, Model: model,
		}
		_ = cm.SaveMessage(ctx, msg)
		return msg, nil
	}
	if err := cm.SetSession(ctx, arg.ConversationID, result.SessionID); err != nil {
		// Best-effort: losing the session id only means the NEXT turn starts a
		// fresh session instead of resuming this one — degraded, not broken.
		_ = err
	}
	msg, action := parseAssistantTurn(arg.PR, arg.ConversationID, arg.TurnID, result.Text)
	// Which model actually answered — the reviewer sees it on the bubble when it
	// isn't the default one (see the model pill in ClaudeChat.mjs).
	msg.Model = model
	if action == nil {
		_ = cm.SaveMessage(ctx, msg)
	}
	return msg, action
}

// chatFailureTurn words one failed attempt for the reviewer and says, through
// its Kind, whether the workflow will try again by itself.
//
// KindRetrying while there is a next rung on the ladder ("nieuwe poging over N
// seconden"), KindError once it is exhausted — at which point only the manual
// "Opnieuw proberen" (chatActionRetry) starts it over. The wording names the
// model of the attempt that failed and of the next one, because a switch from
// Opus to Sonnet is exactly the kind of thing a reviewer should not have to
// guess at; the meaning lives in those words, never in the bubble's colour
// (the colourblind rule).
func chatFailureTurn(attempt int, model string) (kind, body string) {
	total := len(chatRetryDelays) + 1
	failed := fmt.Sprintf("Er ging iets mis bij het praten met Claude (%s). Poging %d van %d mislukt",
		chatModelLabel(model), attempt+1, total)
	if attempt >= len(chatRetryDelays) {
		return chat.KindError, failed + " — dat was de laatste automatische poging. Probeer het handmatig opnieuw."
	}
	next := chatModelForAttempt(attempt + 1)
	return chat.KindRetrying, fmt.Sprintf("%s — nieuwe poging over %d seconden met %s.",
		failed, int(chatRetryDelays[attempt].Seconds()), chatModelLabel(next))
}

// chatProgressThrottle bounds how often a text delta is pushed to the browser.
// The CLI streams a frame per token; forwarding every one of them would be a
// pointless SSE frame storm for something the reviewer reads at human speed.
// A phase/tool change always publishes immediately — that is exactly the
// "what is Claude doing now" signal, and it must never lag behind.
const chatProgressThrottle = 120 * time.Millisecond

// chatProgressSink builds the OnEvent callback that maps modules/claude's
// streamed ChatEvents onto the conversation's volatile progress snapshot and
// pushes it out. Called serially from RunChat's own single reader goroutine
// (see RunRequest.OnEvent), so the captured lastPublish needs no lock.
func chatProgressSink(pr int, conversationID string) func(claude.ChatEvent) {
	var lastPublish time.Time
	return func(ev claude.ChatEvent) {
		snap, ok := mutateChatProgress(conversationID, func(p *chatProgress) {
			switch ev.Kind {
			case claude.ChatEventStatus:
				p.Phase = chatPhaseStarting
			case claude.ChatEventThinking:
				p.Phase = chatPhaseThinking
				p.Tool, p.Detail = "", ""
			case claude.ChatEventTool:
				p.Phase = chatPhaseTool
				p.Tool = ev.Tool
				// A tool block is announced twice (name first, arguments once they
				// have streamed in); never let the second, richer Detail be wiped
				// by the first announcement of the same tool.
				if ev.Detail != "" {
					p.Detail = ev.Detail
				}
			case claude.ChatEventText:
				p.Phase = chatPhaseWriting
				p.Tool, p.Detail = "", ""
				p.Partial += ev.TextDelta
			}
		})
		if !ok {
			return // the turn already finished; a late frame changes nothing
		}
		if ev.Kind == claude.ChatEventText && time.Since(lastPublish) < chatProgressThrottle {
			return
		}
		lastPublish = time.Now()
		publishChatProgress(pr, conversationID, snap)
	}
}

// parseAssistantTurn turns the model's raw text into a chat.Message: a
// KindQuestion turn when the text is exactly the strict "question"
// assistantDirective JSON, a (nil chat.Message, non-nil directive) pair when
// it is a validated "comment_action" directive, otherwise a plain text turn
// (the raw text verbatim — including when it happens to start with "{" but
// doesn't parse as a recognized directive, so a stray/malformed directive
// degrades to plain text rather than vanishing).
// stripEmDash replaces every em dash ("—") with a plain hyphen. Used only on a
// comment_action "reply" body (see parseAssistantTurn) — the reviewer never
// wants that character in a Claude-drafted comment reply, and a system-prompt
// instruction alone isn't a guarantee.
func stripEmDash(s string) string {
	return strings.ReplaceAll(s, "—", "-")
}

func parseAssistantTurn(pr int, conversationID, turnID, text string) (chat.Message, *commentActionDirective) {
	msg := chat.Message{
		ID: chatMessageID(turnID, ""), ConversationID: conversationID, PR: pr,
		Role: "assistant", Body: text,
	}
	trimmed := strings.TrimSpace(text)
	if !strings.HasPrefix(trimmed, "{") {
		return msg, nil
	}
	var d assistantDirective
	if err := json.Unmarshal([]byte(trimmed), &d); err != nil {
		return msg, nil
	}
	switch d.Type {
	case "question":
		if strings.TrimSpace(d.Question) == "" {
			return msg, nil
		}
		opts := d.Options
		if len(opts) > maxChatQuestionOptions {
			opts = opts[:maxChatQuestionOptions]
		}
		msg.Kind = chat.KindQuestion
		msg.Body = d.Question
		msg.Options = opts
		return msg, nil
	case "comment_action":
		if d.Action != "reply" && d.Action != "resolve" {
			return msg, nil // malformed -> degrade to plain text, per the rule above
		}
		if d.Action == "reply" && strings.TrimSpace(d.Body) == "" {
			return msg, nil
		}
		if strings.TrimSpace(d.CommentID) == "" {
			return msg, nil
		}
		body := d.Body
		if d.Action == "reply" {
			// The reviewer never wants an em dash in a Claude-drafted reply — this
			// body lands verbatim in the comment composer via saveChatDraftReply, so
			// sanitize it once here rather than trust the system prompt's wording
			// alone. "resolve" carries no reviewable body (always "/resolve", set by
			// applyChatCommentAction), so it needs no sanitizing.
			body = stripEmDash(body)
		}
		return chat.Message{}, &commentActionDirective{CommentID: d.CommentID, Action: d.Action, Body: body}
	default:
		return msg, nil
	}
}

// applyChatCommentAction is the applyChatCommentAction Activity's body (a
// plain, testable function, mirroring runOneClaudeTurn): validates a
// comment_action directive and, only if it passes every check, applies it.
//
// The two actions diverge on purpose (reviewer's explicit request): "resolve"
// still signals the target comment thread's own task_code_comment Execution
// directly via the EXISTING "reply" Signal (Source "ai") — never a direct
// write, the same sanctioned path an AI code_warning finding already uses —
// because there is no text to review first. "reply" does NOT touch the
// comment thread at all any more; Claude may draft a reply "on the reviewer's
// behalf", but only the reviewer's own edit + explicit send in the comment
// composer ever posts it (see saveChatDraftReply and, on the frontend,
// RelatedPanel.mjs's applyPendingDraftReplies). Every failure is also logged
// via tm.logf, per .claude/rules/workflows-write-boundary.md's best-effort
// convention — never a Go error that would fail the whole workflow.
func applyChatCommentAction(ctx context.Context, tm *TaskManager, arg chatCommentActionInput) {
	d := arg.Directive

	// The directive must target the conversation's OWN thread — a chat has no
	// context about any other comment of the PR, so any other id can only be a
	// hallucination/mistake, never a legitimate cross-thread request. Rejected
	// silently from the reviewer's point of view except for the log line + the
	// KindError turn below; never signalled, never drafted.
	if d.CommentID != arg.ConversationID {
		tm.logf("claude_chat: comment_action ignored — directive commentId=%q does not match conversation=%q (pr=%d)",
			d.CommentID, arg.ConversationID, arg.PR)
		saveChatActionOutcome(ctx, tm.chat, arg, "Kon niet worden toegepast — ongeldige comment-referentie.")
		return
	}
	if d.Action != "reply" && d.Action != "resolve" {
		tm.logf("claude_chat: comment_action ignored — unknown action=%q (pr=%d conversation=%s)", d.Action, arg.PR, arg.ConversationID)
		saveChatActionOutcome(ctx, tm.chat, arg, "Kon niet worden toegepast — onbekende actie.")
		return
	}
	if tm.comments == nil {
		saveChatActionOutcome(ctx, tm.chat, arg, "De comment-thread is niet beschikbaar.")
		return
	}
	c, ok, err := tm.comments.Get(ctx, arg.ConversationID)
	if err != nil || !ok || c.Status == "deleting" || c.Status == "deleted" {
		tm.logf("claude_chat: comment_action skipped — comment %s not found/deleted (pr=%d, err=%v)", arg.ConversationID, arg.PR, err)
		saveChatActionOutcome(ctx, tm.chat, arg, "De comment-thread bestaat niet meer.")
		return
	}

	if d.Action == "reply" {
		// No Signal, no Execution-status check: a draft is never written to the
		// comment thread by itself, so whether that thread's Execution can still
		// receive a Signal is irrelevant here — only the comment row itself must
		// still exist (checked above).
		saveChatDraftReply(ctx, tm.chat, arg, d.Body)
		return
	}

	// d.Action == "resolve" — an immediate action, no text to review first.
	// A completed/failed Execution can no longer receive a Signal — check
	// BEFORE signalling rather than relying on Signal's own error, so the
	// reviewer-facing message can name the real reason (mirrors the avatar-
	// backfill glue's own Status check in comment_import.go).
	status, err := tm.engine.Status(c.RunID)
	if err != nil || status == tembed.StatusCompleted || status == tembed.StatusFailed {
		tm.logf("claude_chat: comment_action skipped — thread %s not signallable (status=%q, err=%v)", c.RunID, status, err)
		saveChatActionOutcome(ctx, tm.chat, arg, "De comment-thread kan niet meer worden bijgewerkt.")
		return
	}

	// A deterministic reaction id for the same reason chatMessageID exists: a
	// replayed Activity must not post the SAME reply into the comment thread
	// twice (comments.AddReaction is an INSERT OR IGNORE on this id).
	sig := ReactionSignal{ID: chatActionReactionID(arg.TurnID), Source: "ai", Author: "Claude", Body: resolveSentinel, Done: true}
	if err := tm.Signal(c.RunID, sig); err != nil {
		tm.logf("claude_chat: comment_action signal failed for %s: %v", c.RunID, err)
		saveChatActionOutcome(ctx, tm.chat, arg, "Kon de comment-thread niet bijwerken. Probeer het opnieuw.")
		return
	}
	saveChatActionOutcome(ctx, tm.chat, arg, "✓ Comment-thread opgelost.")
}

// saveChatActionOutcome records the single visible turn for a comment_action
// "resolve" attempt (or a validation failure of either action): KindAction for
// a text starting with "✓" (the success text built above), KindError for
// anything else — see chat.KindAction's own doc comment.
func saveChatActionOutcome(ctx context.Context, cm *chat.Module, arg chatCommentActionInput, text string) {
	if cm == nil {
		return
	}
	kind := chat.KindError
	if strings.HasPrefix(text, "✓") {
		kind = chat.KindAction
	}
	_ = cm.SaveMessage(ctx, chat.Message{
		ID: chatMessageID(arg.TurnID, "action"), ConversationID: arg.ConversationID, PR: arg.PR,
		Role: "assistant", Kind: kind, Body: text,
	})
}

// saveChatDraftReply records a comment_action "reply" directive's drafted
// body as its own turn (chat.KindDraftReply) — never signalled onto the
// comment thread. A distinct id suffix ("draft") from saveChatActionOutcome's
// ("action") so the two can never collide for the same TurnID; deterministic
// under replay for the same reason chatMessageID exists (modules/chat.SaveMessage
// is an INSERT OR REPLACE on this id).
func saveChatDraftReply(ctx context.Context, cm *chat.Module, arg chatCommentActionInput, body string) {
	if cm == nil {
		return
	}
	_ = cm.SaveMessage(ctx, chat.Message{
		ID: chatMessageID(arg.TurnID, "draft"), ConversationID: arg.ConversationID, PR: arg.PR,
		Role: "assistant", Kind: chat.KindDraftReply, Body: body,
	})
}
